### ISSUE TITLE
How to add or install from `requirements.txt` file?

### ISSUE THREAD

**Issue by Chr1s-T** [mitsuhiko/rye#103]
Need a "read" command to ensure the users can use rye reading `requirements.txt` to install or add the packages totally. Now I have to install from requirements.txt for each package individually, or have to write a shell script to execute this function, which is not official.

**Comment by ischaojie** [comment]
Maybe rye should automatically migrate the `requirements.txt` and `setup.py` that already exist in the project during initialization, like [hatch](https://hatch.pypa.io/latest/intro/#existing-project) does.

**Comment by 9ovn** [comment]
try this commands below:
```shell
source .venv/bin/activate
pip install -r requirements.txt
```
it works fine for me.
it should be a graceful way to handle this problem,like @ischaojie mentioned,the hatch way it`s much graceful.

**Comment by mitsuhiko** [comment]
Closing in favor of #191
