### ISSUE TITLE
Replacing pip-compile with something from Rust-land?

### ISSUE THREAD

**Issue by LarsDu** [mitsuhiko/rye#111]
I noticed that this tool is written in Rust but still relies on pip-compile for dependency resolution:
https://github.com/mitsuhiko/rye/blob/main/rye/src/lock.rs#L232

Are there any plans to swap out pip-compile with something faster written in rust? Perhaps whatever dependency resolver cargo is using?

This certainly won't resolve package metadata retrieval slowness, but this would seem like a good place to leverage the performance of Rust!(?)

**Comment by ischaojie** [comment]
rye uses a wide range of tools from the existing Python ecosystem internally, and it's worth discussing whether it's necessary to re-invent them all over again~

https://github.com/mitsuhiko/rye/blob/5309d73af073c91ba788f267ecc1c1a416bfab0c/rye/src/bootstrap.rs#L28-L44

**Comment by mitsuhiko** [comment]
Well pip-tools need replacing, but I don't care much about it being written in Rust I think. But yes, that is one of the most significant issues with the whole experiment at the moment.
