### ISSUE TITLE
Run `rye sync` automatically after either `rye add` or `rye remove` 

### ISSUE THREAD

**Issue by ifeeltiredboss** [mitsuhiko/rye#114]
[Docs](https://mitsuhiko.github.io/rye/user_guide/#sync-your-python-environment) specify that after `rye add` or `rye remove` we need to run `rye sync` as well. I wonder why these commands are separated. 

IMHO, having automatically synced environment could improve UX a bit.

**Comment by mitsuhiko** [comment]
The only reason they are separated is the appalling performance of `rye lock` and `rye sync` today. But yes, it really should.

**Comment by mitsuhiko** [comment]
With the changes in #121 this feature now becomes somewhat ambiguous as the state of the virtualenv is now also influenced by the features picked on lock/sync.

**Comment by T-256** [comment]
IMO Here an option could be used for those commands: `--sync, --no-sync`
And it can have default settings in `config.toml`.

**Comment by spookyuser** [comment]
Here's a fish script ~~I~~ gpt wrote which seems to work p well for this

```
# Create a custom function named custom_rye_add
function custom_rye_add
    # Run the original rye add command with all passed arguments
    rye add $argv

    # Check if the last command was successful
    if test $status -eq 0
        # Run the sync command
        rye sync --all-features
    else
        # Print an error message and exit
        echo "Failed to add dependency. Not running sync."
        return 1
    end
end

# Save the function so it's available in future sessions
funcsave custom_rye_add

# Create an alias to replace the original rye add command (Optional)
alias rye_add="custom_rye_add"
```

so you just do `rye_add` to get the sync after, i also built in all-features bc on my dev machine i always want all features

**Comment by haoxins** [comment]
> IMO Here an option could be used for those commands: `--sync, --no-sync` And it can have default settings in `config.toml`.

+1 for this.

**Comment by dsp** [comment]
Related pull request: https://github.com/mitsuhiko/rye/pull/677

**Comment by mitsuhiko** [comment]
Closing this as resolved.
