### ISSUE TITLE
Missing lib on ArchLinux when installing through Cargo

### ISSUE THREAD

**Issue by wowi42** [mitsuhiko/rye#15]
*WIP*

```error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory```

this error requires ```libxcrypt-compat```

```pacman -S libxcrypt-compat```

**Comment by wuyudi** [comment]
try this?

https://aur.archlinux.org/packages/rye-git

I have tested, `namcap` did not warn.

**Comment by imbev** [comment]
Perhaps using a musl build or an extracted appimage would solve the problem.

**Comment by mitsuhiko** [comment]
For now since this all installs via cargo only anyways by compiling, i could also switch to build settings that compile an SSL library in the same go.

**Comment by imbev** [comment]
Note that this issue is caused by the Python binary, not the Rye binary. I recommend switching the toolchain sources to extracted appimages

**Comment by quiver** [comment]
I encountered the same error on Amazon Linux 2023.

`$ sudo dnf install libxcrypt-compat` worked for me.

**Comment by mitsuhiko** [comment]
@quiver I presume this happens from the underlying Python for you?

**Comment by imbev** [comment]
> @quiver I presume this happens from the underlying Python for you? At the very least this needs better documentation. The PyOxidizer builds have that in the quirks section: https://gregoryszorc.com/docs/python-build-standalone/main/quirks.html#missing-libcrypt-so-1

I think rye should either bundle the library, or switch to another Python distribution.

**Comment by quiver** [comment]
@mitsuhiko

>  I presume this happens from the underlying Python for you? 

No, this error happens on `rye` installation process, i.e., `$ curl -sSf https://rye-up.com/get | bash`. So I believe this is a rust-specific problem.

**Comment by imbev** [comment]
There is an appimage distribution. It can be extracted to avoid the libfuse dependency, with Apprun replacing the python binary.

I agree that it usually is the host's responsibility, but if rye is to be a "one command install", this should be accounted for.

**Comment by mitsuhiko** [comment]
@quiver can you paste the full output please?

**Comment by quiver** [comment]
@mitsuhiko 
> can you paste the full output please?

Looking at the logs, it's caused by Python installations.

## full output

<img width="1512" alt="image" src="https://github.com/mitsuhiko/rye/assets/266641/7bc256d0-af55-4c42-9732-8b2f1153fbca">

```
sh-5.2$ sudo su - ec2-user
[ec2-user@ip-172-31-35-58 ~]$ uname -a
Linux ip-172-31-35-58.eu-central-1.compute.internal 6.1.27-43.48.amzn2023.aarch64 #1 SMP Tue May  2 04:53:12 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
[ec2-user@ip-172-31-35-58 ~]$ curl -sSf https://rye-up.com/get | bash
This script will automatically download and install rye (latest) for you.
######################################################################## 100.0%
Welcome to Rye!

This installer will install rye to /home/ec2-user/.rye
This path can be changed by exporting the RYE_HOME environment variable.

Details:
  Rye Version: 0.2.0
  Platform: linux (aarch64)

Continue? yes
Installed binary to /home/ec2-user/.rye/shims/rye
Bootstrapping rye internals
Downloading cpython@3.10.11
Checking hash
success: Downloaded cpython@3.10.11
/home/ec2-user/.rye/py/cpython@3.10.11/install/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
Error: failed to initialize virtualenv in /home/ec2-user/.rye/self
```

## How to reproduce

1. Launch Amazon EC2
  - Amazon Linux 2023
  - select arm instance type:t4g.micro 
2. connect to EC2 with Session Manager and sudo to `ec2-user`
3. run `$ curl -sSf https://rye-up.com/get | bash`

**Comment by mitsuhiko** [comment]
This is now documented and a better error message is created on start. Generally though this is a archlinux violation of LSB and a bug should be opened against archlinux.
