### ISSUE TITLE
Documentation for TOML

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#154]
There is not enough documentation today for the `tool.rye` section in the `pyproject.toml`.

Refs #153

**Comment by cnpryer** [comment]
FWIW I really enjoy shallow but effective user guides. So this would be a nice feature to start expanding docs beyond the user guide. The user guide could link to it from its topic section.

Also, it would be nice to sync the order up between the broader docs and the user guide. So currently the order is:

1. Getting started
1. Manage your Python toolchain
1. Start a project
1. Change your current Python version
1. Add a dependency to your project
1. Sync your Python environment with your project
1. Remove a dependency from your project
1. Run a script
1. Install a global tool
1. Manage Rye

It'd be nice to basically click <kbd>></kbd> at the end of each page and follow the same order. All this stuff would be searchable anyway, so if you're looking for `run` docs or `[tool.rye.scripts]` you'd search for it directly anyway.

**Disclaimer**: I haven't distributed many docs myself. I'm just speaking from experience as a user. I feel like the official Rust book is what really solidified this opinion for me.

**Comment by mitsuhiko** [comment]
This is largely resolved now.
