### ISSUE TITLE
Proper Installation

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#155]
Rye needs a proper self installation like rustup. At the very least it needs to register the shims path on `PATH` and probably place rye binary itself in `shims` as well.

**Comment by cnpryer** [comment]
The word *proper* is tripping me up a little, but maybe as a first-pass we could just slap a shell script in a gist and add "run this curl command to install rye" to the docs/readme. 

Basically
```
❯ curl --proto '=https' --tlsv1.2 -sSf https://gist.githubusercontent.com/mitsuhiko/.../raw/.../rye-init.sh | sh
```

When I'm thinking of *proper* installation it'd probably be formally served along with an alternative installer to download.

I'm kinda interested in this one (starting with the gist method), so I'm reading through `rustup-init.sh`. Prior to #156 we'd still rely on cargo, but at least you could get the ball rolling.

**Comment by mitsuhiko** [comment]
I think curl to bash is all we need for a start.
