### ISSUE TITLE
Provide Binaries

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#156]
It should be possible to install rye without having a rust compiler available.

**Comment by cnpryer** [comment]
Not sure where your mind is at with this, but probably could just have an action manage the gh release on a new tag and attach the artifacts. Then link to them from the docs when it's live.

**Comment by mitsuhiko** [comment]
I think something like that yeah. One challenge is that binaries most likely need to be signed so that would require some investigation.

**Comment by ischaojie** [comment]
I've always wanted to be able to install `rye` (for mac or linux users) via `brew install rye`, but the right time might be when the first mature version of `rye` is released.

**Comment by jankatins** [comment]
Starship has some fairly extensive release workflow which includes notarizing the binaries: https://github.com/starship/starship/blob/master/.github/workflows/release.yml

Ripgrep is easier to implement but does not contain signing: https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

I would already be happy if there would be releases with binaries which one could download and use directly (I use starship, ripgrep, rtx and more like that). If it needs signing, that can then be added in a second step :-)

One thing would be nice: having changelog in the release mail generated by github requires either adding the changelog when adding the release of only adding the release in draft mode and then manually adding the changelog and only then publishing it.

I would be happy to add some basic "draft release on tag, upload binaries to release, set release to publish" (and if there is a way: add changelog to the release :-)), if that would be a nice first step.

**Comment by messense** [comment]
IMHO you can build and upload pre-built binary wheels to PyPI with [maturin](https://github.com/PyO3/maturin) just like the way [ruff](https://github.com/charliermarsh/ruff) does.

**Comment by mitsuhiko** [comment]
I started something off the ripgrep builds now. Will take a bit more though until this is complete.
