### ISSUE TITLE
Support Local Python Installations

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#16]
On the version of rye I published there is currently no support for local Python installations. This is pretty much intentional because I really want the experience to not involve manually downloading Pythons. However there are also situations where this is necessary. In the original implementation I had, the way non automatically managed Python installations worked was with registering them.

Link a Python:

```
ln -s /path/to/python ~/.rye/py/my-dst@3.11.0
```

And to pick a default distribution for what gets picked up when you write `3.11.0` another symlink does:

```
ln -s ~/.rye/py/my-dist@3.11.0 ~/.rye/py/3.11.0
```

I however never really fleshed out the details and it was pretty brittle. In particular the only way I found to reliably pin a project to pypy for instance was to write `pypy@madeupversion` into `.python-version` which obviously is not very portable.

Remaining tasks:

* [ ] enable rye to work with a local toolchain entirely (eg: make the `self` venv work with a supplied one)
* [ ] find a good way to pin to specific installations without throwing stuff into the `.python-version` file that other toolchains cannot work with

**Comment by WhyNotHugo** [comment]
`rustup`'s implementation might be a good reference here:

```
rustup toolchain link system /usr
rustup default system
```

I guess making the default configurable is enough to cover this issue; I can already register the system one.

**Comment by cnpryer** [comment]
> find a good way to pin to specific installations without throwing stuff into the .python-version file that other toolchains cannot work with

What about doing something like 
```toml
[tool.rye]
managed = true
standalone-toolchain = false
```
With a predictable resolution strategy for this setting. Could take inspiration from [`py`](https://github.com/brettcannon/python-launcher/blob/bbb89464d9aecc39d19c77686b7957179bafa7b8/src/lib.rs#L350).

**Comment by mitsuhiko** [comment]
Closing this for now. It's possible now to register custom toolchains, for improvements in the handling individual tickets should be opened.
