### ISSUE TITLE
Creating empty virtual envs

### ISSUE THREAD

**Issue by cojua8** [mitsuhiko/rye#166]
Hi!,

I'm looking for a way to set a standalone virtualenv, which will be use as default python by apps like vscode or pycharm or nvim. Is there an existing way to do this?

**Comment by mitsuhiko** [comment]
Can you provide more details about this request? Is this about having some sort of throwaway virtualenv?

**Comment by cojua8** [comment]
yeah!, something like what [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) does

**Comment by mitsuhiko** [comment]
I'm not entirely sure I understand what the point of this is in the context of rye. Can you elaborate how you would use this?

**Comment by cojua8** [comment]
A use example is python neovim, which requires pynvim to be installed. As I don't want to install pynvim globally, I need a virtual environment to install it. It is also not a tool, so it does not quite fit using the install command of Rye.

Another use example is pycharm, which requires a python installation for running its tools I think.

In general, the use case is where another program uses python, but you don't use python or tools directly.

As Rye manages python versions and virtual environments, I think it would be a good thing to have

**Comment by doolio** [comment]
Would [pipx](https://pypa.github.io/pipx/) be a solution? It is what you should use to install python applications globally *for your user*. Unlike `pip` it ensures your local installations do not conflict with each other when they have the same dependency but not necessarily at the same version. It does this by creating separate virtual environments for each application.

````shell
python3 -m pip install --user pipx
python3 -m pipx ensurepath
python3 -m pipx install pynvim
````

**Comment by cojua8** [comment]
pipx is aimed for end-user apps. [pynvim](https://github.com/neovim/pynvim) is just a package, not an end user app, so I think that wouldn't be a solution

**Comment by mitsuhiko** [comment]
Closing this as out of scope for Rye.

**Comment by ma-sadeghi** [comment]
@mitsuhiko Not sure if this was the OP's intent, but here's a use case: I usually work on multiple projects with a general theme (in my case scientific computing) that share many dependencies. What I used to do (and wanted to replicate with `rye`, but couldn't find a clear-cut solution) was to create a shared `conda` virtual environment (e.g., called `dev` or `sci`), which would host all shared and non-shared dependencies of these projects, so every time I wanted to work on one, everything would just work right out of the box without having to constantly switching virtualenvs.

I'm very new to `rye`, but so far, it seems that one way to achieve this in `rye` is to install all those dependencies in the global scope, which doesn't seem like a good idea (?).

**Comment by ma-sadeghi** [comment]
Thanks for the pointer, I'm experimenting with it atm; I think it'll do the job.
