### ISSUE TITLE
Can't install rye due to 404

### ISSUE THREAD

**Issue by theLastOfCats** [mitsuhiko/rye#188]
### Steps to Reproduce

1. curl https://rye-up.com/get | bash

### Expected Result

Rye installs

### Actual Result

404

### Version Info

None

**Comment by cnpryer** [comment]
Could you provide some info about your system? I can't repro on macos.

**Comment by mitsuhiko** [comment]
The issue is that you run `curl rye-up.com/get` instead of `curl https://rye-up.com/get`. That means that you do a HTTP instead of HTTPS request, so the server issues a redirect which curl does not pick up on unless you pass `-L`. Is there a command mentioned somewhere without the https in front?

**Comment by mitsuhiko** [comment]
Closing this. I cannot reproduce this.
