### ISSUE TITLE
Import requirements.txt / setup.py Projects

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#191]
It's quite hard to get started with rye today if one does not have a pyproject.toml project. A possible way would be to have a `rye init --import` command that takes an existing project and makes it work with rye.

* #103

**Comment by cnpryer** [comment]
This would actually be nice for me assuming `poetry export` gets me what I'd want here. Ideally I could export to requirements and then `rye init --import` all my `poetry`-managed projects.

I need to do a little research to better understand the lift here, but assuming it's how I'm imagining it will be, I'd be interested in tackling this.

**Comment by mitsuhiko** [comment]
There is also an alternative world where we support `setup.py` entirely and just dump a `pyproject.toml` next to it with custom config. Not sure if that's a good or bad idea. FWIW I'm open for anything just to get the ball rolling and explore from there.

We could start feature gating some more experimental features so there is more freedom to explore.

**Comment by cnpryer** [comment]
> where we support `setup.py`

Do you mean allow for the package to build and then pull its metadata from the distribution? I like that better tbh.

> Not sure if that's a good or bad idea

One thing that comes to mind so far is that if the user doesn't know to maintain core metadata in the pyproject.toml it might cause some confusion since, iirc, most backends will prioritize the pyproject.toml for metadata.

**Comment by mitsuhiko** [comment]
Since `pyproject.toml` is also used to just configure tools like `black` i think the ecosystem has mostly evolved to disregard partial `pyproject.toml` files.

**Comment by ischaojie** [comment]
I found that `PDM` has a script similar to parse `setup.py` as a reference: https://github.com/pdm-project/pdm/blob/main/src/pdm/models/in_process/parse_setup.py

**Comment by cnpryer** [comment]
Wanted to report this here since it's relevant. I might create another issue for it to PR it if I can get some time.

If you add dev dependencies to a pyproject.toml that isn't originally managed by rye, the tool section initializes like this
```toml
[tool]
rye = { dev-dependencies = [
    "pytest>=7.4.0",
] }
```

Idk how others feel about this topic, but I'd like that initial setup to look something like
```toml
[tool.rye]
dev-dependencies = [
    "pytest>=7.4.0"
]
```

**Comment by mitsuhiko** [comment]
I'm closing this as resolved for now as init can import basic project snow.

**Comment by lmanini** [comment]
fwiw, I found `rye add $(pip freeze) && rye sync` to work with no major issues, aside from having to bump `requires-python` in `pyproject.toml` from time to time

**Comment by cnpryer** [comment]
Personally I've thought about using `uv` under the hood for some imports.

Also, from what I can tell, there's a lot of focus on environment reproducibility. That might tie into project import capabilities.

**Comment by dverdinpno** [comment]
I'm lost on how to actually use a requirements.txt file with rye. 

I've tried `rye init` and had no luck, it just installed an empty project in my existing project. `rye init --import` says it has an unexpected argument. I also tried `source .venv && python -m pip install -r requirements.txt`, but the version of python that rye installed doesn't come with pip.

**Comment by charliermarsh** [comment]
I believe you want `rye init -r requirements.txt`, then `rye sync`. (You shouldn't run pip commands with Rye; Rye intentionally omits pip from the created virtual environment.)

**Comment by UnoYakshi** [comment]
> Wanted to report this here since it's relevant. I might create another issue for it to PR it if I can get some time.
> 
> If you add dev dependencies to a pyproject.toml that isn't originally managed by rye, the tool section initializes like this
> 
> ```toml
> [tool]
> rye = { dev-dependencies = [
>     "pytest>=7.4.0",
> ] }
> ```
> 
> Idk how others feel about this topic, but I'd like that initial setup to look something like
> 
> ```toml
> [tool.rye]
> dev-dependencies = [
>     "pytest>=7.4.0"
> ]
> ```

How does one switch to Rye from existing `pyproject.toml`, though? `rye init --help` doesn't tell how to import an existing `pyproject.toml`. I previously used PDM, and its dev-dependencies look like:
```toml
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.3.1",
    "pytest-asyncio>=0.21.0",
    "httpx>=0.24.0",
    "pre-commit>=3.2.2",
    "black>=23.3.0",
    "isort>=5.12.0",
    "mypy>=1.2.0",
    "sqlalchemy-stubs>=0.4",
    "pep8-naming>=0.13.3",
    "ruff>=0.0.264",
    "safety>=2.3.4",
    "coverage>=7.2.5",
]

[tool.pdm.scripts]
_.env_file = ".env/import_dev.env"
```

**Comment by UnoYakshi** [comment]
Also, is it possible (or planned) for Rye to auto-update `requirements.txt` on `pyproject.toml` dependencies changes?
