### ISSUE TITLE
Documentation for publish command

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#201]
The `publish` command lacks documentation.

**Comment by cnpryer** [comment]
If you want this sooner rather than later I can knock it out. Otherwise I don't want to take away from potential first-timers a good first issue.

**Comment by mitsuhiko** [comment]
Not super urgent. Let's see if someone volunteers :)

**Comment by jbrazf** [comment]
From what I see in the docs, there does not seem any good place for it, should it just be a new doc page/file ?

**Comment by cnpryer** [comment]
IMO a *Publishing* page in the user guide is probably sufficient. Otherwise this is super self-contained. If a new page is overkill it'll be easy to move elsewhere. No harm in giving it a first-pass.

If I were to do this I'd just focus on adding a "Publishing" section and then getting feedback.

**Comment by jbrazf** [comment]
Ah yes, that was what I was thinking. Putting that new page below dependency sources maybe
