### ISSUE TITLE
Replace the outdated create-release action in the release.yml

### ISSUE THREAD

**Issue by ischaojie** [mitsuhiko/rye#210]
actions/create-release has not been maintained for a long time: https://github.com/actions/create-release/issues/119, we can use [softprops/action-gh-release](https://github.com/softprops/action-gh-release) instead.

**Comment by mitsuhiko** [comment]
Yeah, I'm aware it's outdated but it works and I was unable to get the other ones to do what I needed and eventually gave up.

**Comment by ischaojie** [comment]
got it.
