### ISSUE TITLE
Tab completion: `rye run x` should yield completion to the called executable

### ISSUE THREAD

**Issue by whi-tw** [mitsuhiko/rye#213]
### Steps to Reproduce

1. `rye run pyt <tab>`

1. `rye run -- pyt <tab>`

### Expected Result

I'd expect to see the completions of the called command

### Actual Result

No completions, bell sounds

### Version Info

rye 0.2.0
commit: 0.2.0 (d87583862 2023-05-23)
platform: macos (aarch64)
self-python: cpython@3.10
symlink support: true

**Comment by whi-tw** [comment]
This has been achieved nicely in [99designs/aws-vault](https://github.com/99designs/aws-vault/tree/master/contrib/completions) for `bash`,`zsh` and `fish`.

Their implementation uses a switch on `--` - all completion after that sequence is handed off back to the shell's concept of `_normal` (ie. as if you triggered completion with an empty prompt line)

**Comment by mitsuhiko** [comment]
I'm not sure exactly what the ask is here. You can already generate a completion script. Is the ask to automatically install these?

```zsh
eval $(rye self completion -s zsh)
```

**Comment by whi-tw** [comment]
No, sorry, not that.

The ask is that `rye run -- py<tab>` would return the same completion options as if you just typed `py<tab>` on the cli.

This would mean you could use tab completion for commands which are run using `rye run`

**Comment by whi-tw** [comment]
I've written a number of CLI apps which do this, using the patterns in the scripts I linked here: https://github.com/mitsuhiko/rye/issues/213#issuecomment-1561176097 - do you not think those would work in the case of `rye`?

I'm not super au-fait with rust, but I might have a go and see if I can get something working

**Comment by whi-tw** [comment]
oooh, valid point 🤦🏻‍♂️ I had my head in "general-task-runner" mode, not "we're running commands in a very specific environment" mode. 

completely misread this:
> The issue is that the completion would actually depend on what's configured in the scripts or what can be found

**Comment by mitsuhiko** [comment]
I think if this ever gets fixed it might be possible to do something: https://github.com/clap-rs/clap/issues/1232

**Comment by mitsuhiko** [comment]
Closing this for now as I do not believe work here will actually take place.

**Comment by hgaiser** [comment]
I agree with @abdulhaq-e . At the moment `rye` seems to consume any tab event, but it would be nice to do `rye run foo /path/to/<tab>` and have it autocomplete whatever is in that directory. Should this be a new issue?
