### ISSUE TITLE
Adding unstable release fails to find the package

### ISSUE THREAD

**Issue by juhamust** [mitsuhiko/rye#214]
### Steps to Reproduce

According to the documentation (https://rye-up.com/guide/basics/#adding-dependencies), specific packages are installed using the command:

```
rye add "flask>=2.0"
``` 

Therefore, I'd assume an unstable package like [sphinxcontrib-exceltable/0.3.0.dev1](https://pypi.org/project/sphinxcontrib-exceltable/0.3.0.dev1/) should be added to the project using the command:

```
rye add "sphinxcontrib-exceltable==0.3.0.dev1"
```

With the command above, rye fails to find the package.

### Expected Result

An unstable package is added to the project without issues.

### Actual Result

```
Error: did not find package 'sphinxcontrib-exceltable==0.3.0.dev1'
```

### Version Info

```
rye 0.2.0
commit: 0.2.0 (d87583862 2023-05-23)
platform: macos (aarch64)
self-python: cpython@3.10
symlink support: true
```

**Comment by CharlesChen0823** [comment]
current not support dev version requirements search.

**Comment by juhamust** [comment]
Yes 👍 I'm able to add the package with the command:

```
rye add --pre "sphinxcontrib-exceltable==0.3.0.dev1"
```

So perhaps something to add to the documentation, if not there yet 🤔 Feel free to close the ticket if you no actions are needed.

**Comment by mitsuhiko** [comment]
I think this should get both docs and a warning with better explanation in the error message.
