### ISSUE TITLE
add proxy support

### ISSUE THREAD

**Issue by somata-cn** [mitsuhiko/rye#215]
I did not find any information about the proxy in the documentation and source code.
For some reasons, downloading CPython in China is very slow or even impossible, which makes it difficult for me to use rye as a package management tool for Python. Can you add the --proxy parameter to specify the proxy server. Thanks!!!

**Comment by ischaojie** [comment]
You can do this by setting up a system proxy, but it's not a bad idea for `rye` to support the proxy itself.

**Comment by CharlesChen0823** [comment]
I think add proxy for `fetch` command is first priority, other command current has workaround way.

**Comment by somata-cn** [comment]
> You can do this by setting up a system proxy, but it's not a bad idea for `rye` to support the proxy itself.

I have already configured the system proxy on Windows, but this does not work. In other methods, configuring the environment variable 'HTTP_PROXY' is also not work. Can you provide an effective method?

**Comment by CharlesChen0823** [comment]
try setting `CURLOPT_PROXY=http://0.0.0.0:80` ?

**Comment by mitsuhiko** [comment]
It absolutely needs proxy support, but since rye is using a lot of different tools underneath that all talk to the internet, it can be challenging to support this. I will figure out what it takes though.

**Comment by somata-cn** [comment]
I'm so sorry, I didn't restart Windows Terminal, which caused the system proxy configuration to fail on Windows. After the configuration is completed, I can see that pypi.org traffic has passed through the proxy, but the download request for Cpython has not yet passed through the proxy.

**Comment by CharlesChen0823** [comment]
> try setting `CURLOPT_PROXY=http://0.0.0.0:80`(this is an example) ?

@somata-cn  can this work? `pypi.org` can also replace with other source without using proxy.

**Comment by CharlesChen0823** [comment]
i'm sorry for that not work, currently should modify the code to work.

**Comment by CharlesChen0823** [comment]
```
diff --git a/rye/src/bootstrap.rs b/rye/src/bootstrap.rs
index 2db92f2..e44c1d5 100644
--- a/rye/src/bootstrap.rs
+++ b/rye/src/bootstrap.rs
@@ -1,5 +1,6 @@
 use std::borrow::Cow;
 use std::env::consts::{ARCH, EXE_EXTENSION, OS};
+use std::env::var_os;
 use std::io::Write;
 use std::path::{Path, PathBuf};
 use std::process::Command;
@@ -302,9 +303,24 @@ pub fn fetch(
     Ok(version)
 }
 
+fn get_env_proxy() -> Option<String> {
+    let proxy_type: Vec<&str> = vec!["http_proxy", "HTTP_PROXY", "https_proxy", "HTTPS_PROXY"];
+    for v in proxy_type.iter() {
+        let proxy_val = var_os(v);
+        if proxy_val.is_some() {
+            return proxy_val.unwrap().into_string().ok();
+        }
+    }
+    None
+}
+
 pub fn download_url(url: &str, output: CommandOutput) -> Result<Vec<u8>, Error> {
     let mut archive_buffer = Vec::new();
     let mut handle = curl::easy::Easy::new();
+    let has_proxy = get_env_proxy();
+    if has_proxy.is_some() {
+        handle.proxy(&has_proxy.unwrap().as_str())?;
+    }
     handle.url(url)?;
     handle.progress(true)?;
     handle.follow_location(true)?;

```
I think can currently modify this to work.

**Comment by mitsuhiko** [comment]
Maybe someone finds some time to test #219 and see if this works.

```
rye self update --rev 2731cb8eaa5f49c9955feb6d4b0f2bbe70a780fd
```
