### ISSUE TITLE
Linux self update 0.2. -> 0.3 fails to replace python shims

### ISSUE THREAD

**Issue by bluss** [mitsuhiko/rye#224]
### Steps to Reproduce

1. Install 0.2.0
2. rye self update
3. check .rye/shims/python

### Expected Result

.rye/shims/python should be updated to newest version

### Actual Result

rye self update prints an error:
```
> rye self update
Updating to latest
Updated!

Error: No such file or directory (os error 2)
```

Inspect the shims after update and the python, python3 shims are not updated:

```
# rye 0.2.0 (from install)
> sha256sum .rye/shims/*
58d6cc632811ab4a10c6e486f0d9f1068642777d8c9af93d0b235053c1e6480c  .rye/shims/python
58d6cc632811ab4a10c6e486f0d9f1068642777d8c9af93d0b235053c1e6480c  .rye/shims/python3
58d6cc632811ab4a10c6e486f0d9f1068642777d8c9af93d0b235053c1e6480c  .rye/shims/rye
# rye 0.3.0 (from self update)
> sha256sum .rye/shims/*
58d6cc632811ab4a10c6e486f0d9f1068642777d8c9af93d0b235053c1e6480c  .rye/shims/python
58d6cc632811ab4a10c6e486f0d9f1068642777d8c9af93d0b235053c1e6480c  .rye/shims/python3
849ea575a32d17357e6d7448820b71734824498dc2e416d9d8766af1fea00b50  .rye/shims/rye
```

```
cp .rye/shims/python ./rye
./rye --version

rye 0.2.0
commit: 0.2.0 (d87583862 2023-05-23)
platform: linux (x86_64)
self-python: cpython@3.10
symlink support: true
```

OS: Ubuntu 22.04

### Version Info

rye 0.3.0
commit: 0.3.0 (85fc3f6a9 2023-05-27)
platform: linux (x86_64)
self-python: cpython@3.10
symlink support: true

**Comment by mitsuhiko** [comment]
That's a known limitation currently. On Linux (and Windows versions not in developer mode) I am forced to create hardlinks but they are kind hard to swap out later. I have not yet found a reasonable approach for swapping these.

**Comment by bluss** [comment]
I see. Would it work do to the "usual" rename-overwrite that's used for atomic replacement?

```
# in .rye/shims, do the moral equivalent of this
ln rye python.new
mv python.new python
```

**Comment by bluss** [comment]
It is fixed, w.r.t the shims, in 0.4.0.

0.3 -> 0.4 and 0.4 -> 0.4 self update still prints an error message though: `Error: No such file or directory (os error 2)`  (and I'm now not sure why).

**Comment by mitsuhiko** [comment]
@bluss  when do you get that error?

**Comment by bluss** [comment]
It's like it's shown in "actual result" in this report, that's where I get it. It includes the error message.

It wasn't clear to me, but for now I almost have to suspect the error comes from this code in self update:

```rust
    Command::new(env::current_exe()?)
        .arg("--version")
        .status()?;
```
