### ISSUE TITLE
tcl is not included to cpython python 3.11

### ISSUE THREAD

**Issue by seonglae** [mitsuhiko/rye#226]
### Steps to Reproduce

```
rye pin cpython@3.11
rye init
rye sync
python
```

```py
from tkinter import *
Tk()
```

### Expected Result

no error 

### Actual Result

```
Python 3.11.1 (main, Jan 16 2023, 16:02:03) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tkinter import *
>>> Tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
```

### Version Info

```
rye --version
error: unexpected argument found
```

**Comment by mitsuhiko** [comment]
This is sort of expected at the moment. You need to tell TCL where it can find the init.tcl file. I am actually surprised tkinter is still being used which is why I did not bother looking into improving that experience yet.

**Comment by mitsuhiko** [comment]
For now run this before importing tkinter:

```python
import os
import sys
os.environ["TCL_LIBRARY"] = sys.base_prefix + "/lib/tcl8.6"
os.environ["TK_LIBRARY"] = sys.base_prefix + "/lib/tk8.6"
```

The only way in which I can automate this is to set those environment variables. Need to decide if that's a good idea still.

**Comment by mitsuhiko** [comment]
In theory rye could throw a `.pth` file like this into the virtualenv to make it work:

```python
import os, sys; os.environ.setdefault("TCL_LIBRARY", sys.base_prefix + "/lib/tcl8.6"); os.environ.setdefault("TK_LIBRARY", sys.base_prefix + "/lib/tk8.6")
```

**Comment by seonglae** [comment]
> For now run this before importing tkinter:
> 
> ```python
> import os
> import sys
> os.environ["TCL_LIBRARY"] = sys.base_prefix + "/lib/tcl8.6"
> os.environ["TK_LIBRARY"] = sys.base_prefix + "/lib/tk8.6"
> ```
> 
> The only way in which I can automate this is to set those environment variables. Need to decide if that's a good idea still.

This solution works well. Thank you for your help

In other way, `rm -r .venv && python -m venv .venv && pip install -r requirements-dev.lock` also worked if don't want to edit code

**Comment by mitsuhiko** [comment]
@seonglae that's likely because whatever `python` binary is picked up there has some hacks in place to pick up the system tcl version. In general the issue is that Python never really found a good solution to initialize tcl and issues with virtualenvs and TCL require custom hacks in general.

* https://github.com/pypa/virtualenv/issues/56
* https://github.com/pypa/virtualenv/issues/93

There are various things that can be done, but it's unclear what is the least hacky way to accomplish that.

**Comment by seonglae** [comment]
Right. I used global python binary for above solution. Hopefully others will not have to use TK. Thank you for more details.

**Comment by mitsuhiko** [comment]
This will work out of the box in 0.4.0.

**Comment by EthanRosenthal** [comment]
> For now run this before importing tkinter:
> 
> ```python
> import os
> import sys
> os.environ["TCL_LIBRARY"] = sys.base_prefix + "/lib/tcl8.6"
> os.environ["TK_LIBRARY"] = sys.base_prefix + "/lib/tk8.6"
> ```
> 
> The only way in which I can automate this is to set those environment variables. Need to decide if that's a good idea still.

> 

I'm trying to use `rye` with `matplotlib` and the `tkagg` background, and this hack only seems to work for me if I use `rye shell`. Do you have any ideas on how to get this to work if I don't want to spawn a shell?

**Comment by mitsuhiko** [comment]
It sounds to me like the Python running there might not actually be the rye python executable. The `.pth` file has nothing to do with if `rye shell` is used or not. Can you run `which python`?

**Comment by EthanRosenthal** [comment]
`which python` gives the rye shim:

```
/home/er/.rye/shims/python
```
here's `rye show`, in case that's helpful

```
project: my-project
path: /home/er/tmp/my-project
venv: /home/er/tmp/my-project/.venv
target python: 3.8
venv python: cpython@3.11.5
```

I wonder if this is due to a weird interaction with `pyenv` :thinking:

**Comment by EthanRosenthal** [comment]
Ah, wait, you're totally right. The above code was from when I ran `which python` _outside_ of `rye shell`. When I run `which python` within `rye shell`, I get 
```
/home/er/.pyenv/shims/python
```

Back to my original goal which is to be able to use `matplotlib` with `rye`, any idea why the environment variable hack didn't work for me?
