### ISSUE TITLE
Workspace-only projects

### ISSUE THREAD

**Issue by bluss** [mitsuhiko/rye#236]
Workspace-only projects can be used to manage a python environment, with dependencies. What sets it apart from other projects is that it doesn't make sense to install a workspace-only project as a wheel. In theory it does then not need or support a version, a build system, and when "rye sync" runs there is no "self package" that's installed.

Typical usecases: You manage a python environment and installed tools. The project only contains jupyter notebooks and a kernel. The project is just utility scripts that are never installed, only run.

This was discussed on discord, so I thought it would be useful to track it here.

----

Some research:

**Poetry** doesn't have a direct equivalent, but `poetry install --no-root` overlaps with this usecase. The issue 2458 on their issue tracker discusses it.

**Comment by mitsuhiko** [comment]
This absolutely makes sense. In fact the `pyproject.toml` in this particular repository asks for this, as it is only used to pull in mkdocs and dependencies.
