### ISSUE TITLE
Bootstrapping rye internals

### ISSUE THREAD

**Issue by lijc210** [mitsuhiko/rye#24]
$ rye pin 3.11
$ rye run python
Bootstrapping rye internals
error: No such file or directory (os error 2)

**Comment by mitsuhiko** [comment]
Likely run also misses fetching or this is a case of a missing pyproject.toml. Error reporting here is very bad.

**Comment by lijc210** [comment]
I have already executed rye init and it created pyproject.toml.
execute rye pin 3.11  only .python-version was created,I don't know why it doesn't create a Python interpreter

**Comment by mitsuhiko** [comment]
What platform are you on?

**Comment by lijc210** [comment]
Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64

**Comment by mitsuhiko** [comment]
@lijc210 I probably did not fix this yet, but the latest version should at least give better output about what's wrong.

**Comment by mitsuhiko** [comment]
I'm closing this as a duplicate of #30.
