### ISSUE TITLE
an option to not create `.python-version` on init

### ISSUE THREAD

**Issue by T-256** [mitsuhiko/rye#245]
rye also works without this file.

## Example
`> rye init --py PROJECT`

This would not generate python-version file. (As current behavior it will be fallback to use `requires-python`)

**Comment by mitsuhiko** [comment]
We could do a `--no-pin`.

**Comment by T-256** [comment]
> We could do a `--no-pin`.

with `rye init --py 3.7 --no-pin` which one would be used?

**Comment by T-256** [comment]
with above PR, prefer to not create file when both options used.

**Comment by mitsuhiko** [comment]
Closed by #247
