### ISSUE TITLE
Error: IO error: not a terminal

### ISSUE THREAD

**Issue by Code-Hex** [mitsuhiko/rye#246]
### Steps to Reproduce

Run `curl -sSf https://rye-up.com/get | bash` in Dockerfile

### Expected Result

I can install w/o terminal

### Actual Result

```
Welcome to Rye!

This installer will install rye to /opt/rye
This path can be changed by exporting the RYE_HOME environment variable.

Details:
   Rye Version: 0.4.0
   Platform: linux (aarch64)

 Error: IO error: not a terminal

 Caused by:
     not a terminal
```

### Version Info

latest

**Comment by ischaojie** [comment]
Can you provide full Dockerfile content? This error may be caused by your base image with no terminal environment.

**Comment by mitsuhiko** [comment]
@Code-Hex Run with `RUN curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash`. You need a terminal to hit "yes" otherwise.
