### ISSUE TITLE
allow unfinished version when pinning custom toolchain

### ISSUE THREAD

**Issue by T-256** [mitsuhiko/rye#249]
```pwsh
>rye pin x86@3.7
Error: unsupported/unknown version for this platform

>rye pin x86@3.7.9
pinned x86@3.7.9 in .python-version

>rye pin 3.7
pinned 3.7.9 in .python-version

>rye pin cpython@3.7
pinned 3.7.9 in .python-version

>rye pin cpython@3
pinned 3.11.3 in .python-version

>
```
IMO it could allow even `rye pin x86` (without any version) and use its latest version available.

**Comment by mitsuhiko** [comment]
Hidden behind this ticket are really two asks:

1. `.python-version` should encode a version request and not a version itself (eg: `3.7` should ask for latest available `3.7`)
2. `pin` should not try to pin to a specific version

I'm strongly in favor of 1, i'm a bit unsure about how to do 2. I can see two options:

**Pin to latest version by default:**

```bash
rye pin 3.7  # pins 3.7.9
rye pin 3.7 --loose  # pins 3.7
```

**Pin lose by default:**


```bash
rye pin 3.7  # pins 3.7
rye pin 3.7 --precise # pins 3.7.9
```

Or a version of that.

**Comment by mitsuhiko** [comment]
There is also a third ask here which is that for manually registered toolchains, a request also picks the latest available which currently is also not yet supported.

**Comment by T-256** [comment]
> **Pin to latest version by default:**
> 
> ```shell
> rye pin 3.7  # pins 3.7.9
> rye pin 3.7 --loose  # pins 3.7
> ```

yes, it also makes more sense to me too. (I think `loose` naming not good here.)
and note that it should not limit to minor part. (eg. `> rye pin pypy  # pins pypy@3.9.16`)

**Comment by mitsuhiko** [comment]
I think I like neither `--loose` nore `--as-is`. Maybe `--relaxed`?

**Comment by T-256** [comment]
Or `--dynamic` (that more familiar with me maybe bcz of `project.dynamic` in pyproject file)
Or `--expandable` (that points to it would be able expand to the latest version.)

**Comment by mitsuhiko** [comment]
Most of it is I believe supported in #255 now. Would be nice if you could this this. Note that I did not support `rye pin pypy`, you need to do `rye pin pypy@3` at least.  I don't think there is a lot of value in completely version-less pins.

**Comment by T-256** [comment]
> I don't think there is a lot of value in completely version-less pins.

custom toolchains in most of times associated with single version. so that would be nice prevent always write `@...`.

**Comment by mitsuhiko** [comment]
My biggest worry is that it introduces ambiguous syntax. In theory you can already name your custom tool-chain "1234" too.

**Comment by T-256** [comment]
it can solve by limit the toolchain naming to match identity stile. (`str.isidentifier` in py)

**Comment by T-256** [comment]
it's not that much big problem.
