### ISSUE TITLE
Can't install on WSL2 (libcrypt.so.1)

### ISSUE THREAD

**Issue by shohei1029** [mitsuhiko/rye#258]
### Steps to Reproduce

I tried to install rye on WSL2 (Linux) but it failed. I tried on two different machines.
I also tried after installing libcrypt by following commands but didn't affect.
```bash
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install libcrypt1:i386
```

And

```bash
sudo apt-get install libxcrypt-source
```

### Expected Result

Installed successfully.

### Actual Result

<img width="522" alt="image" src="https://github.com/mitsuhiko/rye/assets/7954174/86e5c7f1-b8ac-4347-8bc9-96a8db5be529">

### Version Info

WSL2, Windows 11 (Version 22H2, OS Build 22622.575)

```bash
$ uname -a
Linux sn-slack 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$  bash --version
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
```

```
$  curl --version
curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/1.1.1s zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.51.0 librtmp/2.3
```

**Comment by CharlesChen0823** [comment]
try `sudo apt-get install libssl1.0-dev`?

**Comment by shohei1029** [comment]
Thanks for the advice.

I tried the command but the result was same.

<img width="766" alt="image" src="https://github.com/mitsuhiko/rye/assets/7954174/fcde205a-d9b1-4621-8bdc-da619c4de4ca">

I also renewed the shell session and tried to install the rye but it failed...

**Comment by shohei1029** [comment]
Yes, the version is OpenSSL 1.1.1
<img width="520" alt="image" src="https://github.com/mitsuhiko/rye/assets/7954174/5d9855a4-067a-447b-9296-41bdca9bae20">

**Comment by CharlesChen0823** [comment]
try install file in `http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/` with `sudo dpkg -i XXXnameXXX.deb`

**Comment by mitsuhiko** [comment]
So it looks like ubuntu has removed `libcrypto.so.1` almost completely. I'm not sure what a good course of action is. One option is to have rye ship a version of that library for when it's not available on the system.

**Comment by shohei1029** [comment]
> try install file in `http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/` with `sudo dpkg -i XXXnameXXX.deb`
<img width="513" alt="image" src="https://github.com/mitsuhiko/rye/assets/7954174/2e1f7c19-69b4-4750-a41a-a737875aacaf">

I successfully installed `libssl1.0.0` and `libssl1.0-dev` but unsuccessful for `libcrypto1.0.0-udeb`

```bash
 ✘ shohei@sn-slack  ~/tmp 
  sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb
(Reading database ... 63346 files and directories currently installed.)
Preparing to unpack libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.2n-1ubuntu5.13) over (1.0.2n-1ubuntu5.3) ...
Setting up libssl1.0.0:amd64 (1.0.2n-1ubuntu5.13) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...

 shohei@sn-slack  ~/tmp 
  sudo dpkg -i libssl1.0-dev_1.0.2n-1ubuntu5.13_amd64.deb
(Reading database ... 63345 files and directories currently installed.)
Preparing to unpack libssl1.0-dev_1.0.2n-1ubuntu5.13_amd64.deb ...
Unpacking libssl1.0-dev:amd64 (1.0.2n-1ubuntu5.13) over (1.0.2n-1ubuntu5.13) ...
Setting up libssl1.0-dev:amd64 (1.0.2n-1ubuntu5.13) ...

 shohei@sn-slack  ~/tmp 
  sudo dpkg -i libcrypto1.0.0-udeb_1.0.2n-1ubuntu5.13_amd64.udeb
(Reading database ... 63345 files and directories currently installed.)
Preparing to unpack libcrypto1.0.0-udeb_1.0.2n-1ubuntu5.13_amd64.udeb ...
Unpacking libcrypto1.0.0-udeb (1.0.2n-1ubuntu5.13) over (1.0.2n-1ubuntu5.13) ...
dpkg: dependency problems prevent configuration of libcrypto1.0.0-udeb:
 libcrypto1.0.0-udeb depends on libc6-udeb (>= 2.27); however:
  Package libc6-udeb is not installed.

dpkg: error processing package libcrypto1.0.0-udeb (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libcrypto1.0.0-udeb
```

I also tried to install the ` libc6-udeb` in below two ways but failed.
```bash
 ✘ shohei@sn-slack  ~/tmp 
  sudo dpkg -i libc6-udeb_2.31-0ubuntu9_amd64.udeb
Selecting previously unselected package libc6-udeb.
(Reading database ... 63345 files and directories currently installed.)
Preparing to unpack libc6-udeb_2.31-0ubuntu9_amd64.udeb ...
Unpacking libc6-udeb (2.31-0ubuntu9) ...
dpkg: dependency problems prevent configuration of libc6-udeb:
 libc6-udeb depends on libcrypt1-udeb; however:
  Package libcrypt1-udeb is not installed.

dpkg: error processing package libc6-udeb (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libc6-udeb

 ✘ shohei@sn-slack  ~/tmp 
  sudo apt install libcrypt1-udeb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libcrypt1-udeb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/microsoft-prod.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/microsoft-prod.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/microsoft-prod.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/microsoft-prod.list:1
W: Target Translations (main/i18n/Translation-en_US.UTF-8) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/microsoft-prod.list:1
W: Target Translations (main/i18n/Translation-ja) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/microsoft-prod.list:1
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/microsoft-prod.list:1
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/microsoft-prod.list:1
E: Package 'libcrypt1-udeb' has no installation candidate
```

**Comment by mitsuhiko** [comment]
I think it's best to move this discussion to the underlying builds: https://github.com/indygreg/python-build-standalone/issues/173

I will consider finding a way to ship `libcrypto.so.1` builds with these builds if necessary, but generally a strategy has to be found because if Linux distributions decide on all no longer shipping this library, something needs to be done about it. Sadly binary compatibility and Linux is a really tricky and touchy subject :(

**Comment by bluss** [comment]
Someone mentioned it already but I see mentioned `libcrypto` and `libcrypt` interchangeably, and I think it's good to really clarify which one is meant.

**Comment by shohei1029** [comment]
Yes, it's `libcrypt.so.1`. Strangely, I couldn't install rye after installing libcrypt1 by `apt install`.

![image](https://github.com/mitsuhiko/rye/assets/7954174/8e17e720-5cf8-4d9a-946f-d0f7926db114)

**Comment by mitsuhiko** [comment]
I wonder if the actual problem here is in fact the detection via ldd? I wonder if it would actually work if you were to run the python interpreter directly. Can you try to run `~/.rye/py/cpython@3.11.3/install/bin/python` or whatever it tried to put there?

**Comment by mitsuhiko** [comment]
It sounds like the check on WSL for `libcrypt.so.1` might be wrong then. This is where this check is happening: https://github.com/mitsuhiko/rye/blob/d4a63e984d14edf9818d3488bc0c42415f87c522/rye/src/bootstrap.rs#L433-L467

Maybe `ldd` is lying on WSL, in which case this needs to be either corrected or the check needs to be taken out.

**Comment by mitsuhiko** [comment]
Can you maybe paste the output of `ldd ~/.rye/py/cpython@3.10.11/install/bin/python3`?

**Comment by shohei1029** [comment]
Yes, sure.
```
  ldd ~/.rye/py/cpython@3.10.11/install/bin/python3
        linux-vdso.so.1 (0x00007ffd4d331000)
        /home/shohei/.rye/py/cpython@3.10.11/install/bin/../lib/libpython3.10.so.1.0 (0x00007f204d124000)
        libcrypt.so.1 => not found
        libpthread.so.0 => /home/linuxbrew/.linuxbrew/opt/glibc/lib/libpthread.so.0 (0x00007f204d116000)
        libdl.so.2 => /home/linuxbrew/.linuxbrew/opt/glibc/lib/libdl.so.2 (0x00007f204d111000)
        libutil.so.1 => /home/linuxbrew/.linuxbrew/opt/glibc/lib/libutil.so.1 (0x00007f204d10c000)
        libm.so.6 => /home/linuxbrew/.linuxbrew/opt/glibc/lib/libm.so.6 (0x00007f204d028000)
        librt.so.1 => /home/linuxbrew/.linuxbrew/opt/glibc/lib/librt.so.1 (0x00007f204d023000)
        libc.so.6 => /home/linuxbrew/.linuxbrew/opt/glibc/lib/libc.so.6 (0x00007f204ce12000)
        /lib64/ld-linux-x86-64.so.2 => /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1/lib64/ld-linux-x86-64.so.2 (0x00007f204e43f000)
        libcrypt.so.1 => not found
```

**Comment by shohei1029** [comment]
By the way, is it possible to use [AppImage](https://appimage.org/) format to distribute the rye? I believe the appimage will run in wide range of difference Llinux environments.
