### ISSUE TITLE
workspace pyproject.toml iterator finds project files in .venv

### ISSUE THREAD

**Issue by bluss** [mitsuhiko/rye#260]
### Steps to Reproduce

1. add a dependency that pulls in pyproject.toml somewhere in its installation  (jupyterlab~=3.6)
2. Make the project a workspace
3. Repeated rye sync meets an error, pasted below

Note: rye sync -f is a workaround.

### Expected Result

rye sync should be fine.

I think it looks like the pyproject.toml iterator descends down into .venv and it should probably not do that.

### Actual Result

```
Error: could not write production lockfile for workspace

Caused by:
    project from '.../jupyterlab/.venv/lib/python3.11/site-packages/jupyterlab/tests/mock_packages/test_no_hyphens' has no name
```

### Version Info

rye 0.4.0
commit: 0.4.0 (cdc5c37bc 2023-05-29)
platform: linux (x86_64)
self-python: cpython@3.10
symlink support: true

### Stacktrace

```
Caused by:
    project from '.../jupyterlab/.venv/lib/python3.11/site-packages/jupyterlab/tests/mock_packages/test_no_hyphens' has no name

Stack backtrace:
   0: rye::pyproject::PyProject::normalized_name
   1: rye::lock::format_project_extras
   2: rye::lock::update_workspace_lockfile
   3: rye::sync::sync
   4: rye::cli::sync::execute
   5: rye::cli::execute
   6: rye::main

```

**Comment by mitsuhiko** [comment]
Indeed. Your observation is correct and most likely the correct course of action is to at least ignore `.venv` but probably even go further and ignore some other locations as well.

**Comment by dsp** [comment]
I am curious how you feel about the approach cargo takes and force members to be explicitly defined (similarly to cargo)? It reduces mental load for people coming to a project, having to understand what parts of the configuration are implicit and what are explicit.

It can be a bit annoying to manage but realistically members change rarely and as long as we detect we are inside a workspace and error out if our project is not listed (similarly to cargo).
