### ISSUE TITLE
Windows: Use amd64 toolchain by default

### ISSUE THREAD

**Issue by andrewleech** [mitsuhiko/rye#271]
I know Windows support is early days, but I'm liking using it so far on a couple of projects!

I ran into an issue on a new one just now trying to install a binary wheel for `wxpython`: https://pypi.org/project/wxPython/#files
I eventually traced the failure to the fetched toolchain being the x86 variant.
wxpython, like many (most?) windows binary wheels only publishes for amd64, not x86.

I'd suggest defaulting to amd64 / x86_64 to start with on windows, but ideally allow selecting which arch to install.

**Comment by mitsuhiko** [comment]
I just downloaded rye 0.5.0 on 64bit windows (64bit version)

```
rye init
rye pin 3.10
rye add wxPython
rye sync
```

Results in

```
Initializing new virtualenv in C:\Users\armin\wx\.venv
Python version: cpython@3.10.11
Generating production lockfile: C:\Users\armin\wx\requirements.lock
Generating dev lockfile: C:\Users\armin\wx\requirements-dev.lock
Installing dependencies
Looking in indexes: https://pypi.org/simple/
Obtaining file:///. (from -r C:\Users\armin\AppData\Local\Temp\tmpw8f3q2yh (line 1))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting numpy==1.24.3 (from -r C:\Users\armin\AppData\Local\Temp\tmpw8f3q2yh (line 2))
  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting pillow==9.5.0 (from -r C:\Users\armin\AppData\Local\Temp\tmpw8f3q2yh (line 3))
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting six==1.16.0 (from -r C:\Users\armin\AppData\Local\Temp\tmpw8f3q2yh (line 4))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting wxpython==4.2.0 (from -r C:\Users\armin\AppData\Local\Temp\tmpw8f3q2yh (line 5))
  Using cached wxPython-4.2.0-cp310-cp310-win_amd64.whl (18.0 MB)
Building wheels for collected packages: wx
  Building editable for wx (pyproject.toml) ... done
  Created wheel for wx: filename=wx-0.1.0-py3-none-any.whl size=986 sha256=b0b7b5df24c702bb6e51e43dc3cd7addadb874984ce9df6bf7d3a1de4672a080
  Stored in directory: C:\Users\armin\AppData\Local\Temp\pip-ephem-wheel-cache-rvi8c4tv\wheels\78\12\b9\db4c72ae1aebdfd866f484b59eb7b39f206b7d7d1080ae28b1
Successfully built wx
Installing collected packages: wxpython, wx, six, pillow, numpy
```

I cannot reproduce your issue. Please check that you installed the 64bit build.

**Comment by andrewleech** [comment]
ooh, well I feel foolish now!
![image](https://github.com/mitsuhiko/rye/assets/3318786/964a1ab6-e1e0-4dae-8885-ce8c7fafa965)
I never knew there was a windows x64 version as it wasn't visible on the release assets list... never thought to go hunting under the "Show all 15 assets: button.

**Comment by mitsuhiko** [comment]
Unfortunately I do not have a lot of impact on how this release list renders on github, but the installers are also linked here: https://rye-up.com/guide/installation/
