### ISSUE TITLE
`rye pin cpython@3.8` command was broked

### ISSUE THREAD

**Issue by CharlesChen0823** [mitsuhiko/rye#286]
### Steps to Reproduce

rye init test_pin
cd test_pin
rye pin cpython@3.8

### Expected Result

modifyt .python-version to 3.8.*

### Actual Result

```
charles@charles:~/program/python/test_version$ rye pin cpython@3.8
pinned 3.11.3 in /home/charles/program/python/test_version/.python-version
```

### Version Info

charles@charles:~/program/python/test_version$ rye --version
rye 0.6.0
commit: 0.5.0+93 (53cf0df44 2023-06-02)
platform: linux (x86_64)
self-python: cpython@3.10
symlink support: true

**Comment by ischaojie** [comment]
This should be a bug:
```
➜  o git:(main) ✗ rye pin cpython@3.8
pinned 3.11.3 in /Users/zhezhezhu/projects/test/o/.python-version
➜  o git:(main) ✗ rye pin cpython@3.9
pinned 3.11.3 in /Users/zhezhezhu/projects/test/o/.python-version

```
