### ISSUE TITLE
Using file for license table in pyproject.toml

### ISSUE THREAD

**Issue by cnpryer** [mitsuhiko/rye#287]
Currently initializing with https://github.com/mitsuhiko/rye/blob/1731a5b3721bc3f3a07e3fa7bb9b076215bb1ea3/rye/src/cli/init.rs#L68

I can check again, but from [PEP 621](https://peps.python.org/pep-0621/#license):
> The table may have one of two keys. The `file` key has a string value that is a relative file path to the file which contains the license for the project. Tools MUST assume the file’s encoding is UTF-8. The `text` key has a string value which is the license of the project whose meaning is that of the License field from the [core metadata](https://packaging.python.org/specifications/core-metadata/). These keys are mutually exclusive, so a tool MUST raise an error if the metadata specifies both keys.

So we'd want to use `file` instead of `text` for relative paths IIUC.

**Comment by cnpryer** [comment]
Maybe this is the important part
> the same logic applies to any sort of “type” field specifying what license the file or text represents

**Comment by CharlesChen0823** [comment]
this should be option

**Comment by cnpryer** [comment]
Looks like we still package the license with the distribution that's built, so I'm assuming [this](https://github.com/mitsuhiko/rye/issues/287#issuecomment-1573038744) is why it's fine, but that's confusing.
