### ISSUE TITLE
How to install the environment and dependencies on another computer?

### ISSUE THREAD

**Issue by yorunning** [mitsuhiko/rye#299]
When I clone the project on another computer, how should I install the dependencies? The project includes `pyproject.toml` and `requirements.lock`, but `.venv` is ignored. When I run `rye sync`, it prompts me that there is no venv environment. I want to know how to install dependencies like `npm install`.

terminal error
```
Initializing new virtualenv in D:\dev\testrye\.venv
Python version: cpython@3.11.3
Fatal error in launcher: Unable to create process using '"C:\Users\yorun\.rye\self\Scripts\python.exe"  "C:\Users\yorun\.rye\self\Scripts\virtualenv.exe" -q -p C:\Users\yorun\.rye\py\cpython@3.11.3\install\python.exe --no-seed -- D:\dev\testrye\.venv': ???????????

Error: failed creating virtualenv ahead of sync

Caused by:
    failed to initialize virtualenv
```

**Comment by CharlesChen0823** [comment]
try `rye sync --no-lock`?

**Comment by mitsuhiko** [comment]
Sounds like it's unable to actually create the virtualenv. Not entirely sure why. Can you try running this command?

```
"C:\Users\yorun\.rye\self\Scripts\python.exe" "C:\Users\yorun\.rye\self\Scripts\virtualenv.exe" -p C:\Users\yorun\.rye\py\cpython@3.11.3\install\python.exe --no-seed -- D:\dev\testrye\.venv'
```

**Comment by yorunning** [comment]
yes, it will enter a sub-interactive terminal.

**Comment by mitsuhiko** [comment]
@yorunning can you paste the output of that command?

**Comment by yorunning** [comment]
> @yorunning can you paste the output of that command? @yorunning 你能粘贴那个命令的输出吗？
> 
> (Edit: re-run with the command I pasted, I edited it)（编辑：用我粘贴的命令重新运行，我编辑了它）

I found the problem. I deleted the Python 3.10.11 version that came with the installation of rye, and then reinstalled it. After that, rye sync was able to run correctly. I thought that the 3.10.11 version was no longer needed after I installed the latest version of Python 3.11.3. Thank you for your help.
