### ISSUE TITLE
Confusing Error if Internal Python Builds do not Run

### ISSUE THREAD

**Issue by WhyNotHugo** [mitsuhiko/rye#30]
```
$ rye add atomicwrites
Bootstrapping rye internals
error: No such file or directory (os error 2)
```

With https://github.com/mitsuhiko/rye/pull/29 I get:

```
Bootstrapping rye internals
Error: error bootstrapping venv

Caused by:
    0: unable to create self venv
    1: No such file or directory (os error 2)
```

**Comment by mitsuhiko** [comment]
@WhyNotHugo What CPU architecture and operating system are you on?

**Comment by WhyNotHugo** [comment]
Alpine Edge, amd64.

Not sure if related, but I've no idea where where the 3.10 one came from:

```console
> rye toolchain list
cpython@3.10.9
custom-cpython@3.11.3
```

**Comment by mitsuhiko** [comment]
Alright, so here is what's happening. At the moment rye always uses `cpython@3.10.9` from the indygreg builds. I am assuming that for whatever reason that build is not working for you. Might be worth trying to run this and see what it outputs:

```
$ ~/.rye/py/cpython@3.10.9/install/bin/python3 --version
```

**Comment by WhyNotHugo** [comment]
```
> ~/.rye/py/cpython@3.10.9/install/bin/python3 --version

zsh: no such file or directory: /home/hugo/.rye/py/cpython@3.10.9/install/bin/python3
```

**Comment by mitsuhiko** [comment]
@WhyNotHugo I absolutely understand that desire, but in some sense my goal is to get an experience going first that involves ensuring a working cpython installation from the internet, before going into solving distribution provided python installations. These have been a historic challenge to providing a reliable packaging experience.

**Comment by mitsuhiko** [comment]
@WhyNotHugo this is puzzling

1. does the error still happen if you `rm -rf ~/.rye/py/cpython@3.10.9`?
2. what is the contents of `~/.rye/py/cpython@3.10.9` and `~/rye/py/cpython@3.10.9/install/bin`?

**Comment by WhyNotHugo** [comment]
> my goal is to get an experience going first that involves ensuring a working cpython installation from the internet

But this is _exactly_ the problem that a software distribution solves. E.g.: Alpine has `python3`,  `py3-pip`, etc. Fedora, Arch, OpenBSD, and many others all have equivalent packages.

Your distribution no existing mechanism to have a working Python at all?

**Comment by WhyNotHugo** [comment]
I think this comes down to https://github.com/mitsuhiko/rye/issues/30

**Comment by mitsuhiko** [comment]
I would not say so. Nothing is ever quite as black and white, it's a matter of priorities. The experience I care most about is the one where a developer downloads a tool (let's call it `rye`) which they can use to get a functioning Python installation going on their system that gives them the same experience as on any other system (eg: the `rustup` + `cargo`) experience. This might very well involve having to fall back to system installations of Python, I don't quite know the answer to it.

However what I do know is that priority wise right now is making sure that on systems where the self installed downloaded versions should work, they do work, before looking at system Python installations. System python installations are a huge source of frustration right now because of how many customizations they have.

Here some motivational reasons on this:

* https://github.com/python-poetry/poetry/issues/6371
* https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1967920
* https://github.com/pypa/virtualenv/pull/2415

**Comment by alissonlauffer** [comment]
it doesn't work because Alpine Linux uses musl, and all builds are built against glibc. The "no such file or directory" error is not saying that the executable was not found, but rather the required interpreter (/lib64/ld-linux-x86-64.so.2) wasn't found, since it uses musl.

**Comment by WhyNotHugo** [comment]
Oh, I though that the error had been because `rye` had tried to execute a python which I had not downloaded/fetched first (e.g. Python interpreter not found).

To be honest, I'm pretty discomforted by the fact that `rye` silently downloaded some Python binaries from some random third party source and executed them without any confirmation or indication. `rye` should definitely prompt before doing such things.

In any case, this general approach is a recipe for disaster, you can't just pull binaries from one distribution channel and run them elsewhere and expect them to work. You should never pull binaries from different sources unless they're explicitly built for the target host. Maybe that would work if they're statically linked, but it still sounds like a bad idea with tiny gotchas all over.

This approach of "_my distribution is broken and doesn't ship a working Python, I'll pretend that distributions don't exist and reinvent things from scratch_" is rather childish IMHO, and you're basically making a solution designed for broken distributions and ignoring the non-broken ones. But hey, you build for the future you want to see, so if you want to see a future where these distributions (which don't even ship a working Python) flourish, then this is definitely the way to go.

In any case, this is covered by https://github.com/mitsuhiko/rye/issues/30, there's nothing actionable on this ticket.

> Keep in mind that the Rye project is prioritizing the user experience of having a working Python installation downloaded from the internet.

Yup, it'd been pointed out to me. Regrettably, I'm not looking to switch my Python distribution nor package manager, both the ones I have work for me. I landed here expecting to be able to use rye as a dependency/virtualenv manager, but it's seems this is an all or nothing, so I'll just stick to `pip-tools` and `mkvirtualenv` until somebody tries to build something better on top of what already exists.

**Comment by mitsuhiko** [comment]
Closing this as resolved for now. The error message is better now. For actually supporting MUSL I do not have a plan yet.
