### ISSUE TITLE
Output `rye version` to stdout

### ISSUE THREAD

**Issue by zztkm** [mitsuhiko/rye#307]
I have created the following Makefile and am trying to tag it using `rye version`.

```Makefile
VERSION := $$(make -s show-version)

.PHONY: show-version
show-version:
	@rye version 2>&1

.PHONY: tag
tag:
	@echo "Tagging version $(VERSION)"
	@git tag $(VERSION)
```

However, with the current output method, the `rye version` is output to stderr and needs to be redirected to stdout (as in 2>&1)..

[IMO] It is more intuitive to output `rye version` to stdout.

**Comment by mitsuhiko** [comment]
I'm not opposed but I think a lot of the output of `rye` is currently going to `stderr`, this is not an exception. Might require some rethinking of what should go where.

**Comment by zztkm** [comment]
> Might require some rethinking of what should go where.

My personal opinion is that a simple policy of basically outputting to stdout and errors to stderr is fine.

Also, if there is information that outputting to stdout would result in noise, I think it is better to output to stderr.

**Comment by zztkm** [comment]
> For instance it can sync as part of just running python via the shim, and when it does you don't want this to show up on stdout.

Agreed.

So how about using `println` only in specific cases where it is desirable to output to stdout? In my case, it is version cmd.

**Comment by zztkm** [comment]
I want the discussion to move forward, so I'll add to it.

I want `rye version` to output results like `0.1.0` to stdout. This is the main execution result of rye version, and there should be no problem to output it to stdout.

On the other hand, messages to the user and command progress should be output to stderr.

Example
````
> rye sync
Initializing new virtualenv in /Users/zztkm/dev/sandbox/pydev/rye-version/.venv
Python version: cpython@3.11.3
Generating production lockfile: /Users/zztkm/dev/sandbox/pydev/rye-version/requirements.lock
Generating dev lockfile: /Users/zztkm/dev/sandbox/pydev/rye-version/requirements-dev.lock
Installing dependencies
Looking in indexes: https://pypi.org/simple/
Obtaining file:///. (from -r /var/folders/jf/ppd8_ywn5j94k064g559vgq00000gp/T/tmp8o_qi2pr (line 1))
  Installing build dependencies ... done
```

**Comment by zztkm** [comment]
@mitsuhiko Thank you so much for your support!
