### ISSUE TITLE
Make rye run execute entry points defined in pyproject project.scripts table

### ISSUE THREAD

**Issue by dsp** [mitsuhiko/rye#319]
I have a proposal to run entry points defined in project.scripts through rye run. What I am looking for here is guidance from @mitsuhiko on what the desired semantics in rye should be. I am happy to go and implement it:

# Problem
A common use case for me is to develop a command line tool using rye as the package manager. For example I have a project "simple-cli". However at the moment, there seem to be no way for me to run "simple-cli" using the venv through rye. I need to manually call python with simple-cli. For small projects this is very much acceptable, but for larger projects, it would be much easier to be able to do `rye run` or in a workspace setting `rye run --package $name`, similarly to `cargo run`.

For example in Rust world i can do:
```
$ cargo build
$ cargo run
```

However currently with rye i must do:
```
$ rye build
# ????? how to run the wheel
```

# Proposal
[PEP621](https://peps.python.org/pep-0621/#entry-points) defines the definition of entry points in pyproject.toml files. These are `project.scripts` and `project.gui-scripts` (the distinction being important on windows). These are currently properly embedded into the wheel for setup tools to install them. 

My proposal would be to respect these and make `rye run <name>` being able to run the entry points with the given name from the build artifact (wheel). In case where only one entry point is defined`rye run` should default to the one.

In the end the following should work:
```
$ cat src/cli_test/__main__.py
def main():
    print("Hello world")
$ cat pyproject.toml
[project]
...
[project.scripts]
main = "cli_test:main"
$ rye run
Hello world
```
This should execute something along the lines of
```
python -c 'import sys; sys.path.append(<path to wheel>); from cli_test import main; sys.exit(main())'
```

Note: I am not fully familiar with the entry points and how other package manager deal with executing packages. I might overlook an important definition in the python packaging standard in how to correclty handle this.

## Semantics:
1. User runs `rye run <entry-point>`
     1. rye finds the project (if within a workspace) that has entry-point defined.
     2. rye builds the projects as if `rye build` was called
     3. rye now runs it by
          1. determine the python for the project.
          2. run python with `import sys; sys.path.append(<path-to-wheel>); from <module> import <fn>; sys.exit(<fn>())`. This means we must run it from the wheel, to ensure that we run what we deliver not what is locally on disk in the project.
2. For workspaces all entry points are available. If they are ambiguous the user must specifiy `--package/-p` option to define the package in which to run.

# Considerations
1. Currently `rye run` runs tools but not the projects themnselves. It could be rather confusing to mix tools and packages like that. I personally would love to see `rye tool` and `rye run`, but since we already have tools running through rye run, separating those would be a major break in an early rye.
2. project.scripts is meant for installing scripts, not executing equivalent code directly through the wheel. We must be careful to that rye run must be equivalent to `pip install <wheel>` and then running the `<entry-point>`.
3. We must correclty handle project.scripts and project.gui-scripts on windows.
4. Is running a command from a wheel even a thing in the python world or do we need to consider for command line tools to deliver something like .pex instead and .whl only for libraries?

# Alterantives
Not implementing it :).

**Comment by mitsuhiko** [comment]
I wonder if this is a bug. When I declare a script with `project.scripts`, after `rye build` it shows up in `.venv/bin` (or `Scripts` on Windows) and `rye list` is able to show it.

```
C:\Users\armin\Development\x>rye build
building x
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for wheel...
* Building wheel...
Successfully built x-0.1.0.tar.gz and x-0.1.0-py3-none-any.whl
```

```
C:\Users\armin\Development\x>rye run
hello
pydoc
python
pythonw

C:\Users\armin\Development\x>rye run hello
Hello from x!
```

**Comment by bluss** [comment]
That is confusing, why does the script show up in .venv/bin after rye build? I thought build would only generate the dist artifacts. The `.venv` doesn't even exist after just project init and rye build, for me (linux). I think rye sync is needed.

**Comment by mitsuhiko** [comment]
Actually you are right. The `sync` is what should make it show up.

**Comment by bluss** [comment]
@dsp  Conceptually, "cargo build" and "rye build" don't match. One of the reasons is python wheels, wheels are single packages and they don't contain any dependencies. Cargo by default builds a static binary - embedding everything needed from all Rust dependencies.

So cargo build produces something you can run, and rye build produces a wheel that needs something more before it can run.  (Needs environment, dependencies, install). How would you address that in your suggestion?

**Comment by dsp** [comment]
@bluss I see. I didn't know about rye sync creating these scripts for me. I think the rye sync workflow is fine for now, but i still feel it's a bit confusing as a user. I would expect `<package manager> build` to be the canonical way to build my project and `<package manager> run` the way to run whatever i've just build, which is not true in the current implementation. At the moment i can construct a case, whereas I build something, make a change afterwards, run rye run and see it working but then publish the sdist/wheel without the change with rye publish, since rye build is not synced with rye run.

I do think wheels aren't that much different from a dynamically linked binary. In C/C++/Rust land you would require the local libraries during link time, which is similar to being in a synced venv, and similarly at runtime they need to be in the load path, similarly to rye run. While you can statically link, most are not self-contained and expect an enviroment (which i am painfully aware of as a NixOS user which can't even run rye, since the python binary distributions require shared objects within the load path, which isn't true for NixOS)

**Comment by mitsuhiko** [comment]
I'm not entirely in love with the current flow but there is only so much departure from standard operating principles that folks are used to, that I think can be done without being confusing again.

Maybe both `sync` and `build` are bad terms. In some sense I wish `sync` wasn't necessary at all. I can see a future where the operations that `sync` does become so quick and effortless that they can be done on demand (at least in the common cases). Likewise I can see that `build` in some way is more a "build for dist" kind of experience and maybe should not occupy the command "build" which in other ecosystems might mean different things.

**Comment by bluss** [comment]
@dsp  "build" seems to fit for the current purpose in the python world. "building" a wheel from a pyproject is somehow the foundational layer of the new python packaging tools (starting from PEP 518).  If we say that "build" is the wrong terminology, then we disagree with Python tools head on, it seems.

There's a crate called `build` that orchestrates it, and other workflow tools: hatch, pdm, flit all use a command `build` to mean making wheels and other distributable artifacts.

Also notice in the workflow that your packages are installed in editable mode. If you don't need to install new dependencies or regenerate exactly the project.scripts, then no command at all is usually required to run your program with current changes. There's zero "build/compile" step once the project is already synced once.
