### ISSUE TITLE
Option to disable SSL verify

### ISSUE THREAD

**Issue by 124t** [mitsuhiko/rye#348]
Looking in indexes: https://pypi.org/simple/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))':

I couldn't find an option to disable SSL verification. 

Additionally, I was unable to locate the env file within the .rye directory(I manually added the .rye/shims directory to the path). 
Is it possible that the official documentation(https://rye-up.com/guide/installation/#add-shims-to-path) needs to be updated, or am I missing something? I am using archlinux and have installed the rye package from official sources.

**Comment by mitsuhiko** [comment]
That sounds like a very, very bad idea. Why does the SSL verification fail? But if you really need to do this, but this into your `~/.rye/config.toml`:

```toml
[[sources]]
name = "default"
url = "https://pypi.org/simple/"
type = "index"
verify_ssl = false
```

**Comment by 2gn** [comment]
> Why does the SSL verification fail? 
In my case, I'm in a very limited environment where OS hasn't been updated since 7 years ago. Thus SSL fails. It's our IT guy's problem and there's nothing I can do about this. Also, the server comes with a very old glibc, which disables a lot of programs from running.

I still have the issue after I've added the configuration

```shell
siodfjzx% rye sync
Bootstrapping rye internals
error: could not sync because bootstrap failed

Caused by:
    0: download of https://github.com/astral-sh/uv/releases/download/0.3.0/uv-x86_64-unknown-linux-gnu.tar.gz failed
    1: [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: unable to get local issuer certificate)
```
