### ISSUE TITLE
Global shims do not work on Windows 11

### ISSUE THREAD

**Issue by ShuhuaGao** [mitsuhiko/rye#353]
### Steps to Reproduce

I have enabled global shims.
```powershell
PS C:\Users\lenovo> rye config --get behavior.global-python
true
```
When outside a Rye project, typing `python` will call for Microsoft Store (to install Python), and `python +VERSION` gives no response.
```powershell
PS C:\Users\lenovo> rye toolchain list
cpython@3.11.3 (C:\Users\lenovo\.rye\py\cpython@3.11.3\install\python.exe)
cpython@3.8.12 (C:\Users\lenovo\.rye\py\cpython@3.8.12\python.exe)
PS C:\Users\lenovo> python
PS C:\Users\lenovo> python +3.8.12
```

Note that I have relaunched the terminal after configuring `global-python`.

### Expected Result

Start the Python shims in Rye.

### Actual Result

![1688089439449](https://github.com/mitsuhiko/rye/assets/20141984/1cdb0a1f-dad1-4e98-afb8-8fe2e76dd6d6)

### Version Info

```powershell
PS C:\Users\lenovo> rye --version
rye 0.9.0
commit: 0.9.0 (4fe886c47 2023-06-21)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by ShuhuaGao** [comment]
As a follow-up, the `python` command even does not work in a rye project. It still makes the Microsoft store appear.
First, `PS C:\Users\lenovo\Downloads\wzf\defg> rye sync` succeeded. Then, I typed `python`
```powershell
PS C:\Users\lenovo\Downloads\wzf\defg> python
```
and Microsoft Store showed up.

**Comment by ShuhuaGao** [comment]
> As a follow-up, the `python` command even does not work in a rye project. It still makes the Microsoft store appear. First, `PS C:\Users\lenovo\Downloads\wzf\defg> rye sync` succeeded. Then, I typed `python`
> 
> ```powershell
> PS C:\Users\lenovo\Downloads\wzf\defg> python
> ```
> 
> and Microsoft Store showed up.

Sorry that I made a silly mistake.  I did not move the Shims directory to the top of the path. Now the local `python` works as expected. However, the global `python` still does not work, and the Microsoft Store always appears.

**Comment by T-256** [comment]
what is the output of `where python`?

**Comment by ShuhuaGao** [comment]
> what is the output of `where python`?

![1688438346585](https://github.com/mitsuhiko/rye/assets/20141984/406f5841-d638-4e32-ab4f-50e88b036d99)

The shims directly is added at the top of PATH.

![image](https://github.com/mitsuhiko/rye/assets/20141984/d4b504a7-a52e-49c8-a687-5dfd15890b88)

but it seems that the python.exe in *C:\Users\lenovo\AppData\Local\Microsoft\WindowsApps* is always used instead of the shims one.

**Comment by mitsuhiko** [comment]
This was fixed on master. I pushed out a release now.
