### ISSUE TITLE
encrypt the token content in the file ~/.rye/credentials

### ISSUE THREAD

**Issue by haoxins** [mitsuhiko/rye#373]
I noticed that we are keeping the original token for PyPI in the file located at `~/.rye/credentials`.
Is it better to encrypt the token content with symmetric encryption and store the key in the same file?
This will provide the __weakest protection__ for the token.

**Comment by mitsuhiko** [comment]
The credentials there are already encrypted if you provide a passphrase.

**Comment by haoxins** [comment]
thanks

**Comment by cnpryer** [comment]
Do you have any feedback on how this could potentially be more clear to users? Maybe we can add this to `--help` in some form?

**Comment by haoxins** [comment]
Maybe we can improve the prompt text?

```
Enter a passphrase (optional)
```

maybe we can change it to

```
Enter a passphrase to encrypt the token (optional)
```

**Comment by cnpryer** [comment]
Thats super verbose though.
