### ISSUE TITLE
How do I change the "authors" default in the pyproject.toml?

### ISSUE THREAD

**Issue by BruceEckel** [mitsuhiko/rye#376]
### Steps to Reproduce

1. Search for "authors" in the documentation.
2. Look in in ~/.rye on Unix and %USERPROFILE%\.rye on Windows to see if there's any mention of "authors" in any of the files.
3. Try adding the desired "authors" block to config.toml in the  ~/.rye subdirectory

### Expected Result

Some way to change the 'authors' block

### Actual Result

Nothing I've tried tells me how to do this

### Version Info

rye 0.10.0
commit: 0.10.0 (b822af9a2 2023-07-07)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by BruceEckel** [comment]
Ah, of course -- thanks. I'll just change it in the global git configuration for now.

**Comment by mitsuhiko** [comment]
The latest release lets you set this in the config now too.
