### ISSUE TITLE
Avoid locking projects without source

### ISSUE THREAD

**Issue by T-256** [mitsuhiko/rye#381]
1. `rye init test && cd test`
2. remove `src` folder

The suggestion is `rye lock` should not contain `-e file:.` line.

**Comment by bluss** [comment]
don't you want an explicit marker (like workspace-only) for this? You can have a python library without a src directory, have the files somewhere else.

**Comment by T-256** [comment]
> don't you want an explicit marker (like workspace-only) for this?

it's differed from workspace-only. Currently with above steps, the build backend (e.g. `hatchling`) builds the project successfully, but actually it's empty package (not importable) and only package-info folder exists in `site-packages`.


> You can have a python library without a src directory, have the files somewhere else.

Here I don't mean only `src` folder, it's just example for known build backends that contain source code in `src/{project}` folder. also, the main work here is to detect empty packages before (or after?) building them.
