### ISSUE TITLE
Suggested addition to "Development Dependencies" documentation

### ISSUE THREAD

**Issue by BruceEckel** [mitsuhiko/rye#391]
### Steps to Reproduce

in https://rye-up.com/guide/deps/ under "Development Dependencies" I would suggest adding to the end of that subsection:

To run a tool that has been installed as a development dependency, use `rye run`. For example:
```
> rye run black
```
You may also run the command directly if you are inside a `rye shell`.

### Expected Result

see above

### Actual Result

see above

### Version Info

see above

**Comment by mitsuhiko** [comment]
Fixed in 5912fd03c0786183bf0a20ac34bb043ca25c5853
