### ISSUE TITLE
Rye doesn't install from curl command when /tmp is mounted NOEXEC

### ISSUE THREAD

**Issue by bschonec** [mitsuhiko/rye#392]
### Steps to Reproduce

```
curl -sSf https://rye-up.com/get | bash

curl -sSf https://rye-up.com/get | bash
This script will automatically download and install rye (latest) for you.
######################################################################## 100.0%
bash: line 71: /tmp/.ryeinstall.KIbkIc8X: Permission denied

```

/tmp is mounted NOEXEC

Changing /tmp to EXEC fixes the issue.  

```
nobody@dev-01d:~/$ sudo mount -o remount,exec /tmp
nobody@dev-01d:~/$ curl -sSf https://rye-up.com/get | bash
nobody@dev-01d:~/$ RUST_BACKTRACE=1  curl -sSf https://rye-up.com/get | bash
nobody@dev-01d:~/$ curl -sSf https://rye-up.com/get | bash
This script will automatically download and install rye (latest) for you.
######################################################################## 100.0%
Welcome to Rye!

This installer will install rye to /home/nobody/.rye
This path can be changed by exporting the RYE_HOME environment variable.

Details:
  Rye Version: 0.11.0
  Platform: linux (x86_64)

Continue? [y/n] 
```

### Expected Result

Rye installs

### Actual Result

Rye install fails because /tmp is mounted NOEXEC.

There should be an option to change TMP location or the installer should extract to $PWD.

### Version Info

None yet -- -won't install.

**Comment by cnpryer** [comment]
I'm thinking the following might resolve this

```
TMPDIR=. curl -sSf https://rye-up.com/get | bash
```

https://github.com/mitsuhiko/rye/blob/f45f0cae7b7cb484756a66ef320c7e406c0b8f88/scripts/install.sh#L53

**Comment by cnpryer** [comment]
Reproducing this with rustup I get 
>Cannot execute /tmp/tmp.hlCBMVBvRR/rustup-init (likely because of mounting /tmp as noexec).
>Please copy the file to a location where you can execute binaries and run ./rustup-init.
https://github.com/rust-lang/rustup/blob/87fa15d13e3778733d5d66058e5de4309c27317b/rustup-init.sh#L158-L159

So first thought is, I can probably submit a PR with a similar helpful message. Second thought is, I'm curious if we can't just provide a way to configure what `TMPDIR` is used.

**Comment by cnpryer** [comment]
I have to play with the install script more (not too experienced with this stuff), but a workaround for now is just manually installing using 
```
curl -L -o rye-x86_64-linux.gz https://github.com/mitsuhiko/rye/releases/latest/download/rye-x86_64-linux.gz
gunzip rye-aarch64-linux.gz
chmod -x ./rye-x86_64-linux
./rye-x86_64-linux
```

**Comment by mitsuhiko** [comment]
I am a bit afraid that this problem does not just exist with the installer but also with rye itself. I think at the very least a better error message should be provided for now.

**Comment by mitsuhiko** [comment]
Closing this. The improved error message is I think good enough.
