### ISSUE TITLE
rye sync got error

### ISSUE THREAD

**Issue by jcyongqin** [mitsuhiko/rye#393]
### Steps to Reproduce

1. install rye in a online machine
2. copy ~/.rye dir into a offline machine, without network but have pypi mirror.
3. \# rye init
4. \# rye sync

### Expected Result

expect sync succeed

### Actual Result

Reusing already existing virtualenv
Generating production lockfile: /root/paddlejob/workspace/requirements.lock
Creating virtualenv for pip-tools
FileExistsError: [Errno 17] File exists: '/root/.rye/py/cpython@3.9.16/install/bin/python3' -> '/root/.rye/pip-tools/cpython@3.9/bin/python'
error: could not write production lockfile for project

----

before this error, I fixed /root/.rye/self/pyvenv.cfg. it's contents is old machine's path

### Version Info

rye 0.11.0
commit: 0.11.0 (f6f63d6c1 2023-07-18)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by mitsuhiko** [comment]
I'm not entirely sure what is going on here and I cannot reproduce this. Can you try to delete `/root/.rye/pip-tools` on your offline machine and see if sync work then?

**Comment by jcyongqin** [comment]
By deleting the rye installation files and keeping only the following, rye was successfully up and running on another machine without a network.
- ~/.rye/env
- ~/.rye/shims/
- ~/.rye/py
