### ISSUE TITLE
creating virtualenv fails on pypy

### ISSUE THREAD

**Issue by bluss** [mitsuhiko/rye#395]
### Steps to Reproduce

1. rye init -p pypy@3.9 testpypy
2. cd testpypy
3. rye sync

### Expected Result

Syncs successfully

### Actual Result

```
error: failed creating virtualenv ahead of sync
Caused by:
    No such file or directory (os error 2)
```

The error is caused by the tcl tk path workaround, which hardcodes a path like pythonX.Y inside site-packages, but pypy3.9 uses `.venv/lib/pypy3.9/site-packages/` here.

### Version Info

rye 0.11.0
commit: 0.11.0 (f6f63d6c1 2023-07-18)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by zhuang1234** [comment]
The crux of the question, I think, is why cpython created the folder python, while pypy is still pypy.

**Comment by bluss** [comment]
One could shell out to `python -S -c "import site; print(site.getusersitepackages())"` in the venv but I hope there is a better way to find the name of the directory

**Comment by zhuang1234** [comment]
venv Virtual environments are created by virtualenv. There is a python folder in the lib folder created by cpython, and pypy is created by pypy, and the code only matches python, so it is not found.
