### ISSUE TITLE
rye init issue

### ISSUE THREAD

**Issue by yalunren** [mitsuhiko/rye#400]
When I type "rye init" command without define a project name, it automaticlly creates initial files in the local folder.
I think it's better to show the --help menu instead of just create the file directly.

Thanks.

**Comment by cnpryer** [comment]
This would feel unnatural to me since I interpret `rye init` as "init here" (`rye init .`). I don't interpret it as "tell me more about this command".

**Comment by yalunren** [comment]
> 

OK, I didn't realize rye init = rye init .  The dot is a default directory.
Since it is used for creating a new project, should it better to have user manually define the project name?
Or maybe specifly in documentation that rye init means created project in local folder?

Just some thoughts, thanks.

**Comment by cnpryer** [comment]
@yalunren let me know what you think about #401. Whenever I'm unsure of the usage for a command I'd use `--help`. So hopefully that PR at least makes it more clear.

**Comment by yalunren** [comment]
> @yalunren let me know what you think about #401. Whenever I'm unsure of the usage for a command I'd use `--help`. So hopefully that PR at least makes it more clear.

Got it. Thanks for the update!
