### ISSUE TITLE
Rye sync connection error

### ISSUE THREAD

**Issue by yalunren** [mitsuhiko/rye#402]
### Steps to Reproduce

steps:
> rye pin 3.7.9
> rye sync

It seems due to connection issue, I was unable to finish sync file.
Then I tried to resync again. It tells me unable to run pip-compile.
And I got stuck there.

Thanks.

### Expected Result

finish sync

### Actual Result

PS C:\Users\ya\code> rye sync
Initializing new virtualenv in C:\Users\ya\code\.venv
Python version: cpython@3.7.9
Generating production lockfile: C:\Users\ya\code\requirements.lock
Creating virtualenv for pip-tools
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/pip-tools/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/pip-tools/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/pip-tools/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/pip-tools/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/pip-tools/
ERROR: Could not find a version that satisfies the requirement pip-tools==6.13.0 (from versions: none)
ERROR: No matching distribution found for pip-tools==6.13.0
error: could not write production lockfile for project

Caused by:
    failed to initialize pip-tools venv (install dependencies)

PS C:\Users\ya\code> rye sync
Reusing already existing virtualenv
Generating production lockfile: C:\Users\ya\code\requirements.lock
error: could not write production lockfile for project

Caused by:
    0: unable to run pip-compile

### Version Info

rye 0.11.0
commit: 0.11.0 (f6f63d6c1 2023-07-18)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by ischaojie** [comment]
This doesn't seem to be a problem with `rye`, you need to check your internet connection.

**Comment by yalunren** [comment]
> This doesn't seem to be a problem with `rye`, you need to check your internet connection.

What I mean is I get stuck in this error status. How do I resync the project?
Maybe should have a function like rye sync reset or rye resync? So when user get stuck under these kind situation, he can restart sync the project.

Thanks!

**Comment by yalunren** [comment]
> > This doesn't seem to be a problem with `rye`, you need to check your internet connection.
> 
> What I mean is I get stuck in this error status. How do I resync the project? Maybe should have a function like rye sync reset or rye resync? So when user get stuck under these kind situation, he can restart sync the project.
> 
> Thanks!

I found out that the previous connection error was due to low python version. I was trying to sync python 3.7, apparently, rye doesn't support that version. No wonder rye sync failed.
