### ISSUE TITLE
Why does rye use shims?

### ISSUE THREAD

**Issue by CHRIBUR0309** [mitsuhiko/rye#404]
This is not a criticism, just a question: why does rye use shims? If rye supported Python version management by reattaching paths instead of using shims, as rtx does, it would eliminate the problems caused by shims (which I hear are common in pyenv and asdf, though I don't know much about them). If it's technically difficult to implement the rtx behavior in rye, it's no wonder that rye uses shims.

**Comment by mitsuhiko** [comment]
I’m not familiar with rtx. What does “ reattaching paths” mean?

**Comment by mitsuhiko** [comment]
Shell integrations are very brittle. That's why I really want to avoid going down that path. It increases startup time and requires maintaining a lot of extra complexity for all variations of shells. It also won't work on windows.
