### ISSUE TITLE
`rye install` doesn't work globally, does it?

### ISSUE THREAD

**Issue by makinzm** [mitsuhiko/rye#414]
### Steps to Reproduce

I use MacOS(version 11.7.6, intel-mac).

I thought packages installed by `rye install` can be used globally but my result wasn't this.

1. execute `rye install numpy` (and don't create any projects)
2. `/Users/**/.rye/shims/python3`

```python
Python 3.11.4 (main, Jun 20 2023, 16:52:35) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

### Expected Result

1. execute `rye install numpy` (and don't create any projects)
2. `/Users/**/.rye/shims/python3`
```python
Python 3.11.3 (main, May  7 2023, 19:01:25) [Clang 16.0.3 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = [1,2,3]
>>> np.array(a)
array([1, 2, 3])
```

### Actual Result

```python
Python 3.11.4 (main, Jun 20 2023, 16:52:35) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
```

### Version Info

```rust
rye 0.9.0
commit: 0.9.0 (4fe886c47 2023-06-21)
platform: macos (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by CharlesChen0823** [comment]
try with the document:`https://rye-up.com/guide/tools/`

**Comment by makinzm** [comment]
@CharlesChen0823

Thank you for telling me but I'm not sure how I should do.

However, I realize this sentence, "This for instance allows you to install tools like black or ruff globally",  means that `rye install ` just only support cli tools not common libraries like `numpy`, `matplotlib` and so on.

Is it right?

**Comment by makinzm** [comment]
I think this problem is resolved so I close. Thanks.
