### ISSUE TITLE
Comply with the XDG Base Directory Specification

### ISSUE THREAD

**Issue by doolio** [mitsuhiko/rye#426]
Put rye's `config.toml` under `${XDG_CONFIG_HOME:-${HOME}/.config}/rye`.
Put rye's other data under `${XDG_DATA_HOME:-${HOME}/.local/share}/rye`.

**Comment by mitsuhiko** [comment]
Duplicate of #316. See the last comment there for why I do not want to do this.

**Comment by doolio** [comment]
Apologies for not checking if it was raised already.
