### ISSUE TITLE
bash: register-python-argcomplete: command not found error when spawning a subshell

### ISSUE THREAD

**Issue by doolio** [mitsuhiko/rye#427]
### Steps to Reproduce

I have the following line in `~/.bash_completion` which is sourced by `~/.bashrc` for additional completions.

````shell
eval "$(register-python-argcomplete pipx)"
````
This is how one is instructed to get bash completions for the [pipx](https://pypa.github.io/pipx/installation/#shell-completion) tool and despite not understanding how it works it has been working for me without issue. If I spawn a subshell by executing `bash` I do not see the reported error. However, if within a rye managed project directory and I execute `rye shell` I see the reported error.

### Expected Result

To not observe the reported error.

### Actual Result

![image](https://github.com/mitsuhiko/rye/assets/13859009/1ad72f3a-f9ad-4f9e-ba8f-aa3a28e90320)

### Version Info

rye 0.12.0
commit: 0.12.0 (f5525c985 2023-08-27)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true

### Stacktrace

N/A.

**Comment by mitsuhiko** [comment]
Going to close this as the shell command was removed.
