### ISSUE TITLE
rye shell does not activate environment but does set VIRTUAL_ENV

### ISSUE THREAD

**Issue by doolio** [mitsuhiko/rye#429]
### Steps to Reproduce

1. Create a `rye` managed python project `rye init rye-demo`
2. Navigate into this project directory `cd rye-demo`
3. Execute `rye sync`
4. Execute `rye shell`
5. `echo $VIRTUAL_ENV`

### Expected Result

`rye shell` as advertised should activate the environment when invoked.

### Actual Result

![image](https://github.com/mitsuhiko/rye/assets/13859009/68c39e9b-0b23-4e4a-9edc-601e587a0870)

![image](https://github.com/mitsuhiko/rye/assets/13859009/3896b3a3-336c-4d4f-9199-6a99da3ce5ee)

### Version Info

rye 0.12.0
commit: 0.12.0 (f5525c985 2023-08-27)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true

Note, I have **not** the `rye` shims to my path as they would interfere with my `asdf` shims.

/home/doolio/.local/share/asdf/shims
/home/doolio/.local/share/asdf/bin
/home/doolio/.local/bin
/usr/local/bin
/usr/bin
/bin
/usr/local/games
/usr/games

### Stacktrace

N/A.

**Comment by bluss** [comment]
What is $PATH inside the rye shell? It should have the venv bin directory first.

**Comment by doolio** [comment]
> What is $PATH inside the rye shell? It should have the venv bin directory first.

For me it is the same inside as outside.

![image](https://github.com/mitsuhiko/rye/assets/13859009/f1acb999-1509-401c-9848-edf4a2d8b118)

**Comment by CharlesChen0823** [comment]
IMO, current `rye shell` cannot activate venv as the command `source .venv/bin/activate`.

**Comment by mitsuhiko** [comment]
The current state of the shell command is pretty terrible. I would need to change this to spawn a regular shell and then use something like expect to send commands in to modify `PATH`.

**Comment by CharlesChen0823** [comment]
IMO, we can use `[expectrl](https://github.com/zhiburt/expectrl)` to spawn new shell with `source .venv/bin/activate`.

**Comment by doolio** [comment]
#427 is a related issue to the current status of `rye shell`.

**Comment by mitsuhiko** [comment]
Going to close this as the shell command was removed.
