### ISSUE TITLE
Way to export lock file to requirements.txt?

### ISSUE THREAD

**Issue by bolinocroustibat** [mitsuhiko/rye#431]
Is there a Rye way to export the lock file or the current installed dependencies in the venv to the old standard `requirements.txt` file?

If not, it would be a useful feature. [PDM](https://pdm.fming.dev/latest/usage/dependency/#export-locked-packages-to-alternative-formats) does it nicely, could be an inspiration, e.g.: `pdm export --output requirements.txt --production`

**Comment by mitsuhiko** [comment]
Rye does not have a real lock file. The lock file it generates is literally a requirements file.

**Comment by baggiponte** [comment]
> Rye does not have a real lock file. The lock file it generates is literally a requirements file.

Could rye support still a `rye export --features=a,b,c -o=requirements.txt`? Sometimes I need to deploy a Dockerfile with less dependencies than those locked by default.
