### ISSUE TITLE
Rye+Fish: Add Shims to Path

### ISSUE THREAD

**Issue by hhstore** [mitsuhiko/rye#432]
# Add Fish Env:

- https://rye-up.com/guide/installation/
- The rye documentation does not provide environment variable settings for [fish shell](https://fishshell.com/), I read the `env` file, supplementing the following available setting methods.   
- If you are using `fish`, you can set the environment variables as follows.   
- Alternatively, it can be updated to rye's documentation.

## fix for fish shell:

- add to `~/.config/fish/conf.d/env.fish`:

```ruby

# python + rye: $HOME/.rye/shims
set -gx PATH "$PATH:$HOME/.rye/shims"


```

**Comment by mitsuhiko** [comment]
Do you know if there is a way for fish to source posix shell files? (eg `.rye/env`)

**Comment by hhstore** [comment]
## another solution:

- install a `fish plugin`: [foreign-env](https://github.com/oh-my-fish/plugin-foreign-env) with [oh-my-fish](https://github.com/oh-my-fish/oh-my-fish)

```ruby

omf install foreign-env
```
- edit `~/.config/fish/config.fish` 


```ruby


# fenv + rye: source "$HOME/.rye/env"
if status --is-interactive
  fenv source "$HOME/.rye/env"
end
# rye end


```



## ref:

- https://superuser.com/questions/446925/re-use-profile-for-fish
- https://github.com/rust-lang/rustup/issues/478#issuecomment-330467741
    - rustup set env for `fish shell`.

**Comment by mitsuhiko** [comment]
Sounds like the best thing would be to add this to the docs:

```
set -Ua fish_user_paths $HOME/.rye/shims
```

Maybe print that out as an alternative if fish is detected in the installer.
