### ISSUE TITLE
"error bootstrapping venv" encountered after upgrading to rye 0.13 and attempting rye sync

### ISSUE THREAD

**Issue by ffalcon31415** [mitsuhiko/rye#433]
### Steps to Reproduce

I don't really know how to determine if this is reproducible. This is what I'm experiencing:

1. Have a working rye installation on Windows 10, with rye version 0.11
2. Upgrade to rye 0.12 (didn't test things after that)
3. Upgrade to rye 0.13
4. Execute "rye sync" on a project folder

Thanks!

### Expected Result

Rye would sync

### Actual Result

rye sync

> detected outdated rye internals. Refreshing
> Bootstrapping rye internals
> Found a compatible python version: cpython@3.11.3
> Upgrading pip
> Installing internal dependencies
> error: could not sync because bootstrap failed
> 
> Caused by:
>     0: tried to symlink python shim
>     1: Cannot create a file when that file already exists. (os error 183)

### Version Info

rye 0.13.0
commit: 0.13.0 (8e011231e 2023-08-29)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: false

### Stacktrace

> Stack backtrace:
>    0: <unknown>
>    1: <unknown>
>    2: <unknown>
>    3: <unknown>
>    4: <unknown>
>    5: <unknown>
>    6: <unknown>
>    7: <unknown>
>    8: <unknown>
>    9: <unknown>
>   10: <unknown>
>   11: <unknown>
>   12: <unknown>
>   13: BaseThreadInitThunk
>   14: RtlUserThreadStart

**Comment by ffalcon31415** [comment]
@mitsuhiko 
Done and seems to be working now. Thanks for the help!

**Comment by mitsuhiko** [comment]
I will close this for now. There might be something that when interrupted at the wrong moment breaks.
