### ISSUE TITLE
`rye build` with hatchling backend doesn't include `.data` directory without `--wheel` option

### ISSUE THREAD

**Issue by loqusion** [mitsuhiko/rye#440]
### Steps to Reproduce

> Note: you can reproduce this issue with the `pyproject.toml` in [Hyprshade](https://github.com/loqusion/hyprshade).

1. Have a `pyproject.toml` with [hatchling](https://hatch.pypa.io/latest/) as the backend
2. Include [`shared-data`](https://hatch.pypa.io/latest/plugins/builder/wheel/#options) in the `tool.hatch.build.targets.wheel` to include files in the wheel [`.data` directory](https://peps.python.org/pep-0427/#the-data-directory)
3. Run `rye build`
4. Inspect the wheel with `unzip -l`

### Expected Result

The wheel output of `rye build` should be the same as the wheel output of `rye build --wheel`.

### Actual Result

![image](https://github.com/mitsuhiko/rye/assets/38332081/c8a8c53f-675f-4c14-aee8-f74fd5dc0d9b)

![image](https://github.com/mitsuhiko/rye/assets/38332081/18774415-978f-40f3-9a2b-6aebe6ff7c9e)

### Version Info

rye 0.14.0
commit: 0.13.0+5 (265a0e020 2023-08-31)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by bluss** [comment]
1. build says that it builds the wheel from the sdist. So maybe this is part of the explanation?

```
[tool.hatch.build.targets.sdist]
include = ["src/hyprshade", "tests"]
```

**Comment by loqusion** [comment]
It seems that `build`'s default behavior of building the wheel from the sdist is the reason behind the discrepancy. I was confused because `hatch build` produces the `.data` directory in the wheel regardless of the targets specified, but it looks like hatch is the anomaly and not rye/build.

**Comment by mitsuhiko** [comment]
I added an entry to the FAQ for this. 79f7a3c9a15d109f3b7809f6573fa73c4abeb3c0

**Comment by ofek** [comment]
The next release of Hatchling should raise an error instead https://github.com/pypa/hatch/pull/941
