### ISSUE TITLE
How to set global source for rye config --set

### ISSUE THREAD

**Issue by lijc210** [mitsuhiko/rye#442]
config.toml

[proxy]
http = "http://127.0.0.1:4000"

can to do this:
rye config --set proxy.http=http://127.0.0.1:4000

[[sources]]
name = "default"
url = "http://pypi.org/simple/"

How to set using rye config

the documents:
https://rye-up.com/guide/sources/

**Comment by mitsuhiko** [comment]
You have to set this manually. The config writing tool cannot be used to write array sections.
