### ISSUE TITLE
rye sync downloading python very slow

### ISSUE THREAD

**Issue by yalunren** [mitsuhiko/rye#444]
### Steps to Reproduce

rye pin 3.10.11
rye sync

### Expected Result

finish downloading

### Actual Result

PS C:\Users\yn\git\> rye sync
Python version mismatch (found cpython@3.11.3, expect cpython@3.10.11), recreating.
Downloading cpython@3.10.11
error: failed fetching toolchain ahead of sync

Caused by:
    0: download of https://github.com/indygreg/python-build-standalone/releases/download/20230507/cpython-3.10.11%2B20230507-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst failed
    1: [56] Failure when receiving data from the peer (Recv failure: Connection was reset)

### Version Info

0.11

**Comment by yalunren** [comment]
It download the package very slow, tired using different connection and proxy, still the same. I also tried to set different dependecy source, still doesn't work.

**Comment by mitsuhiko** [comment]
I'm assuming this is a problem on your side. There is not much I can do, rye just uses github to host releases.
