### ISSUE TITLE
SSL Connect error on Windows

### ISSUE THREAD

**Issue by jdumas** [mitsuhiko/rye#457]
### Steps to Reproduce

Running `rye sync` results in `[35] SSL connect error` on my Windows machine. I tried to set up #348 in my `config.toml` to see if it had an effect but no luck. I would appreciate any help debugging this behavior. The issue occurs without being connected to any VPN.

### Expected Result

No error.

### Actual Result

```
❯ rye sync -v
Bootstrapping rye internals
target dir: C:\Users\jedumas\.rye\py\cpython@3.11.5
download url: https://github.com/indygreg/python-build-standalone/releases/download/20230826/cpython-3.11.5%2B20230826-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst
Downloading cpython@3.11.5
error: could not sync because bootstrap failed

Caused by:
    0: failed to fetch internal cpython toolchain cpython@3.11
    1: download of https://github.com/indygreg/python-build-standalone/releases/download/20230826/cpython-3.11.5%2B20230826-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst failed
    2: [35] SSL connect error (schannel: failed to receive handshake, SSL/TLS connection failed)
```

### Version Info

```
rye 0.14.0
commit: unknown (9da44223d 2023-09-16)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: false
```

I am on `Windows 11 Enterprise`

**Comment by mitsuhiko** [comment]
I'm assuming you have a corporate proxy set by your system administrator. Could this be?

**Comment by jdumas** [comment]
It could be, I'm actually not sure. I recently started having SSL/TLS issues on this Window machine and I'm still investigating what's going on. E.g. after upgrading to Chocolatey 2.0 I ran into [this error](https://docs.chocolatey.org/en-us/choco/troubleshooting/unable-to-load-service-index#ssl-tls-errors). I followed the steps described but it didn't solve the issue.

I realize this is not a specific rye issue, but would you mind pointing me to the code responsible for downloading cpython that produced the error above? It'll help me investigate what's going on.

**Comment by mitsuhiko** [comment]
The specific download is taking place here: https://github.com/mitsuhiko/rye/blob/26931a97776e25ca34aab0c54e5d0ba67d53ee5d/rye/src/bootstrap.rs#L393-L454

The failing call is here: https://github.com/mitsuhiko/rye/blob/26931a97776e25ca34aab0c54e5d0ba67d53ee5d/rye/src/bootstrap.rs#L442-L444

I'm assuming an SSL certificate is presented which curl (via schannel) has not loaded.

**Comment by jdumas** [comment]
Thanks! I will investigate a bit more and let you know if I make any progress.

**Comment by Syrus-at-Philips** [comment]
@mitsuhiko, I encounter a similar error with my corporate MITM proxy (Cisco Umbrella):

```PowerShell
~ on ☁️  (us-east-1)
❯ rye self update
Updating to latest
error: could not download release latest for this platform

Caused by:
    0: download of https://github.com/mitsuhiko/rye/releases/latest/download/rye-x86_64-windows.exe failed
    1: [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.)

~ on ☁️  (us-east-1) took 2s
```

Something similar happens with a default conda/mamba installation that is set to use schannel. It uses the native certificates, but also does a revocation check. To get mamba to work, we need to set an option to prevent `curl` from doing the SSL revocation check. This may be needed for `rye` on corporate machines that are running these types of MITM proxies. Either that or an option to bypass SSL. (I know that sounds bad, but the Cisco Umbrella actually does all the SSL checks itself.)

I do have a copy of the 3rd party certificate. So, it would also work if I could configure `rye` to use that certificate file. I didn't see an option like that in the documentation, but maybe I missed it.

Anyway, I like where you are going with `rye`. On the same machine, I'm able to install and download toolchains under WSL in Ubuntu. But I think we would all like to get it working in the native Windows environment.

Thanks for all your efforts and contributions!

**Comment by Syrus-at-Philips** [comment]
By bypass SSL, I mean bypass validation. But still use the `https://` prefix.

**Comment by majidaldo** [comment]
> It could be, I'm actually not sure. I recently started having SSL/TLS issues on this Window machine and I'm still investigating what's going on. E.g. after upgrading to Chocolatey 2.0 I ran into [this error](https://docs.chocolatey.org/en-us/choco/troubleshooting/unable-to-load-service-index#ssl-tls-errors). I followed the steps described but it didn't solve the issue. Note that I can always download the url directly from my webbrowser (Firefox/Chrome).
> 
> I realize this is not a specific rye issue, but would you mind pointing me to the code responsible for downloading cpython that produced the error above? It'll help me diagnose the problem.

then please close. the only rye-related "issue" is how it might proxy settings.

**Comment by mitsuhiko** [comment]
I believe this is resolved in latest version for windows users. I'm closing this for now. Please reopen if this still happens in 0.18.
