### ISSUE TITLE
Document how to configure shell completion

### ISSUE THREAD

**Issue by xzmeng** [mitsuhiko/rye#471]
It would be helpful for users who aren't familiar with shell configuration.

**Comment by magicwenli** [comment]
try `rye self completion <shell name. eg: bash>`

https://github.com/mitsuhiko/rye/blob/952581aa18a2a8947f3b6e847261d4b452806108/rye/src/cli/rye.rs#L52-L58

Hope this can be fix

**Comment by bluss** [comment]
Or per user (no sudo)

```
rye self completion > ~/.local/share/bash-completion/completions/rye.bash
```

**Comment by kkiyama117** [comment]
> try `rye self completion bash > /usr/share/bash-completion/completions/rye.bash`

This may be slightly incorrect. `rye self completion -s bash > (your_shell_completion_path)` may be better.  
In any case, we would appreciate a clearer indication how to configure shell completion.
