### ISSUE TITLE
Some way of exposing the path to the Python interpreter that the rye shim is using?

### ISSUE THREAD

**Issue by chris-laplante** [mitsuhiko/rye#474]
It would be helpful for me if there was a way to detect whether the running Python interpreter is being provided by the rye shim, and also to learn the path to the actual interpreter. Maybe set an environment variable that points to the actual interpreter, e.g. _RYE_SHIM_INTERPRETER = /home/chris/my_project/.venv/bin/python3

For context, we use a tool called BitBake (written in Python) to build our embedded Linux images. I recently started Rye and really like it. At the root of my project I've got a pyproject.toml with the dependencies of BitBake. The issue is that BitBake will sometimes perform builds in temporary directories (under /tmp) that require Python. When those parts of the build are spawned, the Rye 'python3' shim is found on the PATH (because BitBake sanitizes PATH of most every host tool except for Python and a few others, e.g. host GCC). When the shim is executed it obviously cannot find the pyproject.toml. I have global shims turned off.

If I knew the location of the actual python3 that Rye is using, I could inject another hosttool directory into PATH so that Rye can find an interpreter to use. E.g. it would be like this:

PATH = "/home/chris/.rye/shims/python3:/path/to/real/python/bin/:${PATH}"

**Alternatively**, another approach that would work for me is if there was an environment variable that re-roots where Rye looks for pyproject.toml.  

I am certainly willing to submit a PR if you think this is something useful.

**Comment by mitsuhiko** [comment]
You can already get that path by printing out `sys.executable`.

```
C:\Users\armin\Development\rye>python -c "import sys; print(sys.executable)"
C:\Users\armin\Development\rye\.venv\Scripts\python.exe
```

Do you need more than that?

**Comment by mostthingsweb** [comment]
That may be enough, thanks. I'll play with it a little.
