### ISSUE TITLE
Python can't be run via shim, opens Microsoft Store, after clean install 0.15.2 on Windows 11 x64

### ISSUE THREAD

**Issue by iki** [mitsuhiko/rye#480]
### Steps to Reproduce

1. install rye 0.15.2 `rye-x86_64-windows.exe`
2. run `%UserProfile%\.rye\shims\python.exe`

### Expected Result

Python 3.11.6 is executed from `%UserProfile%\.rye\py\cpython@3.11.6\install\python.exe`

### Actual Result

No output on console, Microsoft Store opens.

Notes:
- Python.exe can be run from `%UserProfile%\.rye\py\cpython@3.11.6\install\python.exe` successfully.
- However, Is it correct location, where rye expects it? I saw `..\bin\python.exe`  in comments in other issues here. Imo that should be  documented.
- Setup passed ok, I tried it twice (on first attempt, Windows returned classic localized message that Python can't be found)

```
C:\Users\iki\Downloads\.dev>rye-x86_64-windows.exe
Welcome to Rye!

Rye has detected that it's not installed on this computer yet and
automatically started the installer for you.  For more information
read https://rye-up.com/guide/installation/

This installer will install rye to C:\Users\iki\.rye
This path can be changed by exporting the RYE_HOME environment variable.

Details:
  Rye Version: 0.15.2
  Platform: windows (x86_64)

Continue? yes
Installed binary to C:\Users\iki\.rye\shims\rye.exe
Bootstrapping rye internals
Downloading cpython@3.11.6
Checking checksum
success: Downloaded cpython@3.11.6
Upgrading pip
Installing internal dependencies
Updated self-python installation at C:\Users\iki\.rye\self

Note: You need to manually add %USERPROFILE%\.rye to your PATH.
For more information read https://mitsuhiko.github.io/rye/guide/installation

All done!
Press any key to continue
```

### Version Info

```
C:\Users\iki\.rye\py\cpython@3.11.6>rye --version
rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true

C:\Users\iki\.rye\py\cpython@3.11.6>ver
Microsoft Windows [Version 10.0.22635.2483]
````

**Comment by iki** [comment]
Thanks for a great tool @mitsuhiko! I'm available for any testing

**Comment by iki** [comment]
Strange it works after closing and reopening terminal, even when the env path is unchanged and I tried to run python.exe directly in the shims directory (and with shims path explicitly).

Closing for now, will reopen if it happens again and will be more clear, that there's something to fix

**Comment by iki** [comment]
Strange it works after closing and reopening terminal, even when the env path is unchanged and I tried to run python.exe directly in the shims directory (and with shims path explicitly).

Closing for now, will reopen if it happens again and will be more clear, that there's something to fix

**Comment by iki** [comment]
Resolution of the above issue:

- The python.exe that opens Microsoft Store is a Microsoft shim in `%UserProfile%\AppData\Local\Microsoft\WindowsApps`, which is next python in `PATH` after `%UserProfile%\.rye\shims`
- Rye shim apparently runs the next python in `PATH` when launched outside of any project and [global shim](https://rye-up.com/guide/shims/#global-shims) is not enabled via `rye config --set-bool behavior.global-python=true`

**Comment by mitsuhiko** [comment]
I wonder if I could detect the windows store version. You probably never want to bring up the store and I could instead of falling back to that print out a helpful error.

**Comment by iki** [comment]
@mitsuhiko good idea.

It can be detected by checking if the next python in PATH is `%UserProfile%\AppData\Local\Microsoft\WindowsApp\python.exe`

Actually if there's no global python installed, then `global.python` should be forced true IMO, because user simply wants to run python. Optionally, the setting could be renamed to `override.global.python` to make the logic apparent: if false, it will prefer the existing global python in PATH, if any. WDYT?

**Comment by mitsuhiko** [comment]
> It can be detected by checking if the next python in PATH is `%UserProfile%\AppData\Local\Microsoft\WindowsApp\python.exe`

Not entirely because that executable turns into the actual shim executable when python has been successfully installed from the store.

**Comment by 0x0elliot** [comment]
not very familiar with windows but from what i observed:
- there is a env variable called "Path" that is responsible for linking executables.
- "Path" contains a list of links to the exact directory where your executable might be present.
- So for example, if you want to make "python" work on CMD, you need to make sure that there is a path added to the "Path" which must have "python.exe" in the first depth itself. 

Going off of this: Would it be okay to assume that the windows store would open if you tried replicating the 3rd step and didn't find an appropriate path?
