### ISSUE TITLE
TOML `inline table list` is not working.

### ISSUE THREAD

**Issue by chatblanc-ciel** [mitsuhiko/rye#485]
### Steps to Reproduce

In `pyproject.toml`, I think same meaning below two samples.
```
[tool.rye]
sources = [
    { name = "torch", url = "https://download.pytorch.org/whl/cu121", type = "index" }
]
```
``` 
[[tool.rye.sources]]
name = "torch"
url = "https://download.pytorch.org/whl/cu121"
type = "index"
```

But `inline table list` does not work.

### Expected Result

enable to reference to sources when sources is `inline table list`.
We expect work with this.
```
[tool.rye]
sources = [
    { name = "torch", url = "https://download.pytorch.org/whl/cu121", type = "index" }
]
``` 
```
# requirments.lock
torch==2.1.0+cu121
```

### Actual Result

Only work with `table list`.
``` 
[[tool.rye.sources]]
name = "torch"
url = "https://download.pytorch.org/whl/cu121"
type = "index"
```

When I use `inline table list`, 
```
[tool.rye]
sources = [
    { name = "torch", url = "https://download.pytorch.org/whl/cu121", type = "index" }
]
``` 
I see this result.
```
# requirments.lock
torch==2.1.0
```

### Version Info

```
rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: false
```

**Comment by mitsuhiko** [comment]
That is currently quite intentional. The source lookup expects an array of tables. Maybe something that can be changed though.

**Comment by chatblanc-ciel** [comment]
Thank you for reply.

OK, I understand current state.
When I use multiple sources, I think `inline table` is  good for looking(human readable).
I stay open this issue so that rye get enhancement in the future.

**Comment by chatblanc-ciel** [comment]
@mitsuhiko 
Thank you for responding!
We will continue to support you.
