### ISSUE TITLE
Installer not opening

### ISSUE THREAD

**Issue by sxarthur** [mitsuhiko/rye#487]
### Steps to Reproduce

Trying to Install Rye, it warned me about Developer Mode
I enabled it, closed it, and tried opening again to install, but now it's not opening anymore - it instantly closes

Steps
1 Open Installer

### Expected Result

Installer to Start

### Actual Result

Installer Closing instantly

### Version Info

Latest?

**Comment by mitsuhiko** [comment]
Try to run the installer from `cmd.exe` and see what happens.

**Comment by sxarthur** [comment]
I found out there was a leftovers folder somewhere and also cleaned registry and now it works
