### ISSUE TITLE
Environment broken when I rename or change folder path of project

### ISSUE THREAD

**Issue by seonglae** [mitsuhiko/rye#491]
### Steps to Reproduce

`.venv` activation process broken when I rename or change folder path of project
## Reproduction
```bash
mkdir project1
cd project1
rye init
rye add mypy
rye sync
cd ../
mv project1 project2
cd project2
source .venv/Scripts/activate
.venv/Scripts/dmypy
```

### Expected Result

Even after rename or moving project folder, first `rye sync` automatically update current folder path to environment

### Actual Result

Environment not activated and when I run binary  like `.venv/Scripts/dmypy`
```
Fatal error in launcher: Unable to create process using '"C:\Home\Projects\AI\project1\.venv\Scripts\python.exe"  "C:\Home\Projects\AI\project2\.venv\Scripts\dmypy.exe" ': The system cannot find the file specified.
```
This error couldn't resolved even after retried `rye sync` or changing all `project1` to `project2` in `.venv/Scripts/activate` script.

### Version Info

Test environment is Windows
```
rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by mitsuhiko** [comment]
Virtualenvs need recreation after they are moved. But rye really needs to detect that itself and fix it.
