### ISSUE TITLE
Expose cmd entry points of dependencies directly

### ISSUE THREAD

**Issue by nixjdm** [mitsuhiko/rye#492]
### Feature Request:

Consider pytest, flask, lektor, ansible, etc.

Some installable python packages come with their own entry points. With `pip` and in any other manager I have experience with (conda/poetry/venv/...), the project dependency's entry points can be, or are by default, directly exposed on in the CLI. With rye these dependencies are _only_ accessible via `rye run`. It would be nice to have them also directly exposed, according to the venv that is currently active through rye. That would be in line with what many people are used to, and also faster to type.

Thank you for rye, btw. I'm hoping this is or spurs a better solution to managing environments :)

**Comment by mitsuhiko** [comment]
You can do that by activating the virtualenv. To make them available in other ways would require integrating into the shell which is not something I want to do.

**Comment by nixjdm** [comment]
Bumping this, if the reason for not wanting to do this was time and effort, maybe it could be given a second shot now that Astral's maintaining Rye as well?
