### ISSUE TITLE
Initial rye sync after init does not work "No module named 'click'"

### ISSUE THREAD

**Issue by sil-lnagel** [mitsuhiko/rye#493]
### Steps to Reproduce

Hey, thanks for releasing this! :) I was really looking for some tool that also manages standalone python installations because of the clashes with the distro's packages.

But it looks like the current version has an issue:

1. rye init test03
2. cd test03
3. rye sync

### Expected Result

rye sync completes without an error.

### Actual Result

```
Initializing new virtualenv in /home/lukas/Desktop/ryetest/test03/.venv
Python version: cpython@3.10.6
Generating production lockfile: /home/lukas/Desktop/ryetest/test03/requirements.lock
Generating dev lockfile: /home/lukas/Desktop/ryetest/test03/requirements-dev.lock
Installing dependencies
Traceback (most recent call last):
  File "/home/lukas/.rye/pip-tools/cpython@3.10/bin/pip-sync", line 5, in <module>
    from piptools.scripts.sync import cli
  File "/home/lukas/.rye/pip-tools/cpython@3.10/lib/python3.10/site-packages/piptools/__init__.py", line 5, in <module>
    from click import secho
ModuleNotFoundError: No module named 'click'
error: Installation of dependencies failed
```

### Version Info

rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by mitsuhiko** [comment]
I cannot reproduce this. If this is still happening please try to remove the `~/.rye` folder and re-install rye.
