### ISSUE TITLE
Add `rye list` to list installed packages

### ISSUE THREAD

**Issue by Kydlaw** [mitsuhiko/rye#494]
Most package managers allow to see the installed packages using a variation of a `list` command.

- `pip list` - https://pip.pypa.io/en/stable/cli/pip_list/
- `poetry show` - https://python-poetry.org/docs/cli/#show
- `pipenv graph` - https://pipenv.pypa.io/en/latest/commands/
- `hatch dep show` - https://hatch.pypa.io/latest/cli/reference/#hatch-dep-show

If I understand correctly, `rye` took its inspiration from Cargo using the `cargo install --list` style.

I personally struggled to find how to display the installed packages and only figured it out when researching this issue. However, I understand that an additional command for this specific action might be unnecessary.

Would it make sense to add a list command?

Alternative solutions: Highlight the existing command in the documentation.

**Comment by bluss** [comment]
`rye tools list` - the command already exists. Is this a request to add an alias?

**Comment by gaia** [comment]
it's `rye tools list`

**Comment by TillerBurr** [comment]
That only shows the globally installed tools, not the ones that exist inside a given virtual environment, which I think @Kydlaw is talking about. Since rye doesn't expose pip, you can't use `pip list` to show the installed packages. The only way to do this currently is to install pip via rye and then do a `pip list`.

**Comment by Kydlaw** [comment]
As @TillerBurr mentioned `rye tools list` list the tools that are globally available to Rye (like a formater, a linter, ...).
I finally found the command I was looking for after further exploration: `rye show --installed-deps`.

I think the previous confusion reinforce my point that accessing the installed dependancies of a project is currently not easily feasible.
Also, knowing that a command already exists, `rye list` could be an alias to `rye show --installed-deps`.
