### ISSUE TITLE
Using rye without project name and version in pyproject.toml

### ISSUE THREAD

**Issue by garam-kim1** [mitsuhiko/rye#498]
Thank you for your wonderful library!

Since my goal is not to create a Python package but rather to conduct ML research using Python, it would be helpful if I could omit writing the project name and version in pyproject.toml, to prevent rye from building the package every time, as shown below:
```
Found existing installation: my-project 0.1.0
Uninstalling my-project-0.1.0:
  Successfully uninstalled my-project-0.1.0
...
Successfully built my-project
Installing collected packages: my-project
Successfully installed my-project-0.1.0
```

**Comment by T-256** [comment]
I think you need https://github.com/mitsuhiko/rye/pull/309
