### ISSUE TITLE
Cannot sync a project with python 3.6

### ISSUE THREAD

**Issue by milos7250** [mitsuhiko/rye#511]
### Steps to Reproduce

```shell
$ pyenv install 3.6.15
$ rye toolchain register ~/.pyenv/versions/3.6.15/bin/python
$ mkdir test_project && cd test_project
$ rye init
$ rye pin 3.6
$ rye sync
``` 

### Expected Result

Rye syncs the project properly, initializing a venv with python version 3.6.15

### Actual Result

```
Initializing new virtualenv in ~/test_project/.venv
Python version: cpython@3.6.15
RuntimeError: failed to query ~/.pyenv/versions/3.6.15/bin/python3.6 with code 1 err: '  File "~/.rye/self/lib/python3.11/site-packages/virtualenv/discovery/py_info.py", line 7\n    from __future__ import annotations\n    ^\nSyntaxError: future feature annotations is not defined\n'
error: failed creating virtualenv ahead of sync

Caused by:
    failed to initialize virtualenv
```

I've only replaced the full path prefix of files with `~`. The error is probably caused by changes in the `future` python module across versions. I was trying to find out how to make rye use python3.6 while creating the venv, but I did not succeed. I'll be grateful for any advice on this problem.

### Version Info

```
rye 0.15.2
commit: 0.15.2 (e2beb3a90 2023-10-04)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true
```

**Comment by milos7250** [comment]
Ah, my bad then. Although I don't think I came across this information when I was reading the docs.

**Comment by mitsuhiko** [comment]
Yeah, 3.7 is the lower bar. Sorry for that.
