### ISSUE TITLE
Invalid script entry point when rye sync

### ISSUE THREAD

**Issue by geoqiao** [mitsuhiko/rye#531]
### Steps to Reproduce

`mkdir test_script`
`cd test_script/`
`rye init .`
success: Initialized project in /Users/geoqiao/test_script/.
  Run `rye sync` to get started
`rye add requests`
Added requests>=2.31.0 as regular dependency
`rye sync` failed with: 
`ERROR: For req: test-script==0.1.0. Invalid script entry point: <ExportEntry hello = test:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.`
<img width="737" alt="image" src="https://github.com/mitsuhiko/rye/assets/105639506/c135edd0-b1ac-4805-b905-c2f442b1674a">

### Expected Result

Successfully  `rye sync`

### Actual Result

`rye sync` failed with: 
`ERROR: For req: test-script==0.1.0. Invalid script entry point: <ExportEntry hello = test:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.`
<img width="737" alt="image" src="https://github.com/mitsuhiko/rye/assets/105639506/c135edd0-b1ac-4805-b905-c2f442b1674a">

### Version Info

rye --version
rye 0.16.0
commit: 0.16.0 (c003223d5 2023-12-16)
platform: macos (aarch64)
self-python: cpython@3.11
symlink support: true

**Comment by geoqiao** [comment]
update:
`rye sync` works when the project name does not contain ”-” or “_”

like that : 
mkdir test
cd test 
rye init .
rye add requests
rye sync 
it works

It seems to be a problem with the punctuation in the name of the project

**Comment by peter-fm** [comment]
Same issue on windows
rye 0.16.0
commit: 0.16.0 (c003223d5 2023-12-16)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: true

**Comment by PeterBlackledge** [comment]
Can also confirm the same issue on Windows.

FWIW:
after running 'rye init .' - delete the section [project-scripts] in pyproject.toml - then 'rye sync' runs successfully.

**Comment by geoqiao** [comment]
> Can also confirm the same issue on Windows.
> 
> 
> 
> FWIW:
> 
> after running 'rye init .' - delete the section [project-scripts] in pyproject.toml - then 'rye sync' runs successfully, regardless of hyphens in the project name. 
> 
> 

Thanks for your help. It works when delete the section [project-scripts].
And I find it has been fixed in https://github.com/mitsuhiko/rye/commit/e8404f1c77123be47c95d199426813e2cabaafe7
