### ISSUE TITLE
The 'python' shim fails if it can't find the home folder

### ISSUE THREAD

**Issue by noamraph** [mitsuhiko/rye#532]
### Steps to Reproduce

Assuming you have a python installed at `/usr/bin/python`, and rye installed, run this:

```bash
env - PATH=$HOME/.rye/shims:/usr/bin python
```

### Expected Result

See the Python prompt

### Actual Result

```
error: could not determine home folder
```

### Version Info

rye 0.16.0
commit: 0.16.0 (c003223d5 2023-12-16)
platform: linux (x86_64)
self-python: cpython@3.11
symlink support: true

### Background

I'm using Bazel to build something, and got this error. It took me some time to realize that it's because of `~/.rye/shims/python`. It turns out that Bazel (at least in my case) removes most environment variables (by using `env -`), but still keeps PATH.

Does the `python` shim really need to find the home folder? Even if it does need it when running from a rye project, I think it shouldn't fail if it isn't running the Python of a Rye project - it should just continue to look through the PATH to find the `python` executable.

I would be happy to try and implement a fix, if this is approved.

**Comment by mitsuhiko** [comment]
Agreed that this is not great. I was unaware that such variables would disappear in practice. I will try to add a workaround for this.
