### ISSUE TITLE
Error updating rye on Windows 10 from 0.18 to 0.19 - first attempt only

### ISSUE THREAD

**Issue by ffalcon31415** [mitsuhiko/rye#549]
### Steps to Reproduce

1. Running Microsoft Windows [Version 10.0.19044.3803]
2. Rye 0.18 installed and working
3. Execute `C:\>rye self update`

### Expected Result

It updates successfully to 0.19

### Actual Result

Fails with error on first attempt. Succeeds on second attempt.
```
Microsoft Windows [Version 10.0.19044.3803]
(c) Microsoft Corporation. All rights reserved.

C:\users\USER>rye self update
Updating to latest
Checking checksum                                                                                                      
error: tried to symlink python shim

Caused by:
    Cannot create a file when that file already exists. (os error 183)

C:\users\USER>rye self update
Updating to latest
Checking checksum                                                                                                      
Updated!

rye 0.19.0
commit: 0.19.0 (676b1bffa 2024-01-21)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: false
```

Note the same thing happened when upgrading from 0.17 to 0.18.

Obviously this is a minor (negligible) inconvenience but I thought I'd report it because it might throw somebody off.

Thanks for all the great work on this project!!

### Version Info

was 0.18.0
now:
```
rye 0.19.0
commit: 0.19.0 (676b1bffa 2024-01-21)
platform: windows (x86_64)
self-python: cpython@3.11
symlink support: false
```

**Comment by mitsuhiko** [comment]
This will happen if rye is currently in use and cannot be updated. That is a limitation of the updater on Windows. For others running into this please shut down processes currently using rye (Python interpreters running for instance) and restart the update. I will try to improve the error message.

**Comment by mitsuhiko** [comment]
Closing this as addressed for now.
