### ISSUE TITLE
"rye install datasette" doesn't put anything in ~/.rye/shims

### ISSUE THREAD

**Issue by simonw** [mitsuhiko/rye#57]
### Steps to Reproduce

I just released a new version of Datasette - [0.64.3](https://docs.datasette.io/en/stable/changelog.html#v0-64-3) - which adds the `setuptools` and `pip` dependencies which were causing it to break in Rye (see https://til.simonwillison.net/python/rye#user-content-failing-and-then-succeeding-to-install-datasette)

1. `rye install datasette` - this succeeds
2. But... I would expect to be able to run `~/.rye/shims/datasette --version` - but that file does not exist
3. `~/.rye/tools/datasette/bin/datasette --version` does work

### Expected Result

I expected `~/.rye/shims/datasette` to be created.

### Actual Result

It wasn't created.

### Version Info

```
rye 0.1.0
commit: unknown (c137b62c1 2023-04-26)
platform: macos (aarch64)
self-python: cpython@3.10
```

**Comment by simonw** [comment]
What's particularly weird is that prior to releasing Datasette 0.63.3 the `rye install datasette` command DID put something in `~/.rye/shims/datasette` - but running that command would produce an error because it needed something from `setuptools`.

**Comment by mitsuhiko** [comment]
So I cannot reproduce this for `rye install datasette`:

```
$ rye install datasette
[snip]
$ which datasette
/Users/mitsuhiko/.rye/shims/datasette
```

However I can reproduce it for installing a zipfile locally. See #56 for the issue there.

**Comment by simonw** [comment]
Huh! In that case I imagine what's happened here is specific to my environment - I've run `rye install ...` and `rye uninstall datasette` a bunch of different times in different combinations.

**Comment by simonw** [comment]
Confirmed - I removed `~/.rye` entirely and tried again and it worked as it should:
```
~ % rm -rf ~/.rye
~ % rye install datasette
Bootstrapping rye internals
Downloading cpython@3.10.9
success: Downloaded cpython@3.10.9
Upgrading pip
Installing internal dependencies
Downloading cpython@3.11.1
success: Downloaded cpython@3.11.1
Collecting datasette
  Using cached datasette-0.64.3-py3-none-any.whl (232 kB)
...
Installing collected packages: typing-extensions, sniffio, setuptools, PyYAML, python-multipart, pluggy, pip, pint, mergedeep, MarkupSafe, itsdangerous, idna, hupper, h11, click, certifi, asgiref, aiofiles, uvicorn, Jinja2, janus, click-default-group-wheel, asgi-csrf, anyio, httpcore, httpx, datasette
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.2 PyYAML-6.0 aiofiles-23.1.0 anyio-3.6.2 asgi-csrf-0.9 asgiref-3.6.0 certifi-2022.12.7 click-8.1.3 click-default-group-wheel-1.2.2 datasette-0.64.3 h11-0.14.0 httpcore-0.17.0 httpx-0.24.0 hupper-1.12 idna-3.4 itsdangerous-2.1.2 janus-1.0.0 mergedeep-1.3.4 pint-0.20.1 pip-23.1.2 pluggy-1.0.0 python-multipart-0.0.6 setuptools-67.7.2 sniffio-1.3.0 typing-extensions-4.5.0 uvicorn-0.21.1
installed script datasette
~ % ~/.rye/shims/datasette --version
datasette, version 0.64.3
```

**Comment by mitsuhiko** [comment]
Yeah, rye only places itself in `~/.rye` and then the virtualenvs it creates in your projects in `.venv`.
