### ISSUE TITLE
rye 0.4.0 on windows is virus

### ISSUE THREAD

**Issue by oligamiq** [mitsuhiko/rye#578]
### Steps to Reproduce

1. download installer from rye-up

1. update to 0.4.0 by `rye self update`

### Expected Result
Edge downloaded it.

Run cmd

### Actual Result
Edge is blocked download it.

windows blocked because virus.

![image](https://github.com/mitsuhiko/rye/assets/69239094/f42a2776-cd88-4bfa-8f7e-d30be8011eb5)

![image](https://github.com/mitsuhiko/rye/assets/69239094/a28f4b9c-70d4-4833-8409-5d425e0e66d8)
![image](https://github.com/mitsuhiko/rye/assets/69239094/59e71298-8a42-49f0-bcc8-f483e5aee886)

### Version Info

I cannot cmd now.
but 0.4.0.

**Comment by mitsuhiko** [comment]
Unfortunately nothing I can do here. Whatever software you are using to do virus scanning is probably picking up on a bad signature. We had this before (#468).

You can just download the installer on the website manually, bypass the protection on the dialog and continue.
