### ISSUE TITLE
Add an Option to Prevent .venv from Syncing to Cloud Storage

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#585]
It was brought up in https://github.com/mitsuhiko/rye/issues/371#issuecomment-1925895817 that one of the uses for moving virtual envs to a different location is to prevent them from synching to dropbox. An alternative option would be to have an option in `config.toml` that marks a virtualenv appropriately with the right markers to prevent synching.

```toml
[behavior]
venv-mark-sync-ignore = true
```

This would set the following attributes on the created `.venv` folder:

* `com.dropbox.ignored` on all platforms using dropbox (xattr on unix, NFTS ADS on Windows)
* `com.apple.fileprovider.ignore#P` on macOS

Unfortunately I'm not aware of a way to make this work for Google Drive or OneDrive.

**Comment by mitsuhiko** [comment]
It will work for iCloud Drive but I have not found a way for Google Drive and OneDrive yet.

**Comment by aitirga** [comment]
Hi, is this feature implemented on uv? Or how could I set it up in uv generated .venv folders?
Thanks
