### ISSUE TITLE
Rye seems to pick "latest fetchable" instead of "latest available" for global shims

### ISSUE THREAD

**Issue by seasonedfish** [mitsuhiko/rye#586]
### Steps to Reproduce

1. Upgrade rye using your package manager (I upgraded from 0.15.2 to 0.19.0 using nix)
2. Run the shim `~/.rye/shims/python`

### Expected Result

For rye to use the Python version I installed previously, cpython@3.12.0 (/Users/fisher/.rye/py/cpython@3.12.0/install/bin/python3)

### Actual Result

```console
[fisher@workshop home-manager]$ python
error: Requested Python version (cpython@3.12.1) is not installed. Install with `rye fetch`
[fisher@workshop home-manager]$ rye toolchain list
cpython@3.12.0 (/Users/fisher/.rye/py/cpython@3.12.0/install/bin/python3)
cpython@3.11.6 (/Users/fisher/.rye/py/cpython@3.11.6/install/bin/python3)
cpython@3.8.18 (/Users/fisher/.rye/py/cpython@3.8.18/install/bin/python3)
```

### Version Info

```
rye 0.19.0
commit: 0.19.0 (1980-01-01)
platform: macos (aarch64)
self-python: cpython@3.11
symlink support: true
```

**Comment by mitsuhiko** [comment]
I wonder if this is because when it looks for `3.12` it picks the latest fetchable instead of the latest available. Does this happen with the 0.21 as well?

**Comment by mitsuhiko** [comment]
Could it be that the pin in your `.python-version` file is too specific? Eg: could it show `3.12.0` instead of `3.12`?

**Comment by mitsuhiko** [comment]
I verified this now and the logic will need adjustments. It currently always prefers a downloadable version if the pin is not specific. Eg if you have a `.python-version` pin for `3.12` and you only have `3.12.0` but `3.12.1` is available for download, it will prefer fetching.

**Comment by seasonedfish** [comment]
Thanks so much! Sorry I came back too late to be helpful with debugging haha.
