### ISSUE TITLE
Rye 0.21.0 cannot locate pip

### ISSUE THREAD

**Issue by raanasn** [mitsuhiko/rye#594]
### Steps to Reproduce

Script:

`$ curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash`
`$ . "$HOME/.rye/env"`
`$ rye sync --no-lock`

### Expected Result

Downloading cpython@3.9.18
Checking checksum
success: Downloaded cpython@3.9.18
Initializing new virtualenv in /builds/plan-d/carexpert_ai/ce_quickpredict_ml_webservice/.venv
Python version: cpython@3.9.18
Installing dependencies
Creating virtualenv for pip-tools
Looking in indexes: https://pypi.org/simple/

### Actual Result

Downloading cpython@3.9.18
Checking checksum
success: Downloaded cpython@3.9.18
Reusing already existing virtualenv
Installing dependencies
**error: could not locate pip
Caused by:
    No such file or directory (os error 2)**

### Version Info

`0.21.0`

**Comment by mitsuhiko** [comment]
I'm quite confused that it tried to download 3.9. Can you wipe the `.rye` folder and re-run this? It might be that it picked up an old installation and the upgrade did not function.

**Comment by raanasn** [comment]
@mitsuhiko I wanted python 3.9 and added this to the pyproject.toml:

`requires-python = ">=3.9"`

First it installs 3.12.1 like this: 

_Bootstrapping rye internals
Downloading cpython@3.12.1_

Then when it comes to `$ rye sync --no-lock` it installs this: 

_Downloading cpython@3.9.18_

But fails because of pip.

**Comment by mitsuhiko** [comment]
Can you please dump the output of `rye --version`?

**Comment by nrydanov** [comment]
Got same error, this error occurs with Rye version 0.19.0. Currently, we downgraded Rye to 0.19.0, what solves the issue.

**Comment by mitsuhiko** [comment]
Same question, can you share the output of `rye --version`? I was not able to repro this on my machine yet and would need the full dump of what the version output generates.

**Comment by raanasn** [comment]
@mitsuhiko this did not fix it.

Here is additional Info:

<img width="352" alt="Bildschirm­foto 2024-02-06 um 09 29 08" src="https://github.com/mitsuhiko/rye/assets/11279681/9056ac76-a145-40d4-8947-b4dd1aaa8dd3">

<img width="371" alt="Bildschirm­foto 2024-02-06 um 09 29 30" src="https://github.com/mitsuhiko/rye/assets/11279681/480f24e0-70dc-4586-ab11-944325ff88be">

**Comment by raanasn** [comment]
@mitsuhiko will this be fixed in the next version or should I create a new issue for that?

**Comment by eifinger** [comment]
I had the same issue and investigated a bit in this draft PR: https://github.com/eifinger/setup-rye/pull/153

[1st commit](https://github.com/eifinger/setup-rye/pull/153/commits/85ec8640a5075ea5dc987e679abca7fa1b0dd92c) , just using `rye sync --no-lock` failed : [link to run](https://github.com/eifinger/setup-rye/actions/runs/7831070698)

[2nd commit](https://github.com/eifinger/setup-rye/pull/153/commits/801d10ce7aa85f028b93cf64155614419127eccf) , just updating the lock files with 0.21.0 locally and pushing again failed : [link to run](https://github.com/eifinger/setup-rye/actions/runs/7831151471)

[3rd commit](https://github.com/eifinger/setup-rye/pull/153/commits/c4b1b36791bb62c552795ec3e79e9bce8b85c5b7) , running `rye sync` once before `rye sync --no-lock` succeeded : [link to run](https://github.com/eifinger/setup-rye/actions/runs/7831171206)

**Comment by mitsuhiko** [comment]
Please open a new issue if this still reproduces on the latest version.

**Comment by raanasn** [comment]
@mitsuhiko works perfectly on the latest version! Thanks a lot!

**Comment by eifinger** [comment]
Also fixed on my end. Thanks!
