### ISSUE TITLE
Remove shell command

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#601]
The shell command (`rye shell`) cannot be implemented without allocating a pseudo terminal. That’s not super hard to do but it comes with various restrictions that are inherent to the operation. I’m starting to think that this is something that has too many warts and I would thus prefer to just remove the command.

Users can still activate the virtualenv anyways and the operation is easy enough and well understood.

**Comment by cnpryer** [comment]
Yea makes sense. However, I've been curious of what kind of features can be supported through a controlled terminal the tool could spawn vs interacting directly with the current terminal.

Are there certain issues you ran into that triggered this? I haven't looked at the code in a bit, but back when I was thinking about this I was considering checking out [`rexpect`](https://github.com/rust-cli/rexpect) to see if it'd help make a `shell` command more doable.

**Comment by mitsuhiko** [comment]
Right now it does not work at all as the login shell overrides `PATH`. The way in which other tools prepare a shell involves allocating a pseudoterminal and sending key presses in. At that point you need to handle `SIGWINCH` and so forth. I have been doing this before (https://github.com/mitsuhiko/teetty) but it's always full of corner cases.
