### ISSUE TITLE
RYE_TOOLCHAIN env variable doesn't work

### ISSUE THREAD

**Issue by vanyasvl** [mitsuhiko/rye#603]
### Steps to Reproduce

Hello.
Installer env var RYE_TOOLCHAIN doesn't work, I tried to install Rye with Python 3.11, but it's downloading 3.12

```
curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" RYE_TOOLCHAIN="3.11.7" bash
This script will automatically download and install rye (latest) for you.
warning: this script is running as root.  This is dangerous and unnecessary!
######################################################################## 100.0%
Welcome to Rye!

This installer will install rye to /root/.rye
This path can be changed by exporting the RYE_HOME environment variable.

Details:
  Rye Version: 0.21.0
  Platform: linux (aarch64)

Installed binary to /root/.rye/shims/rye
Bootstrapping rye internals
Downloading cpython@3.12.1
```

### Expected Result

Expect to download and install python 3.11.7

### Actual Result

It downloads Python 3.12

### Version Info

rye --version
rye 0.21.0
commit: 0.21.0 (2e0e02459 2024-02-03)
platform: linux (aarch64)
self-python: cpython@3.12
symlink support: true

**Comment by mitsuhiko** [comment]
`RYE_TOOLCHAIN` cannot be used to point the internal toolchain to a path of a toolchain that already exists. It's not intended to point a specific Python version. Can you clarify why you would want to do that? This is just used for the internal tooling. It is not for the toolchain that is used for your application. For that it picks up the `.python-version` file in your project.

**Comment by vanyasvl** [comment]
I use python 3.11.7 in my project and building a Docker container with Rye to build it. And I don't want to install both Python 3.12 and 3.11 into container due to time and container size. Can I use Rye with 3.11 internal toolchain?

**Comment by mitsuhiko** [comment]
That's not possible today but that would be a good feature request. I will close this ticket and open one for that.
