### ISSUE TITLE
main branch fails with "0: unable to create virtualenv folder" wen syncing an existing venv

### ISSUE THREAD

**Issue by dsp** [mitsuhiko/rye#609]
### Steps to Reproduce

1. Clone recent rye
2. Built commit dbfdeeb90110e87754498d46ac46fca65578e80a (main as of writign this bug)
3. Use an older rye to create a project and sync: `rye-old init rye-test && cd rye-test && rye-old sync`.
4. Sync with rye from main `rye sync`

### Expected Result

Synching successfully

### Actual Result

```sh
$ rye sync
detected outdated rye internals. Refreshing
Bootstrapping rye internals
Found a compatible python version: cpython@3.12.1
Upgrading pip
Installing internal dependencies
Reusing already existing virtualenv
Generating production lockfile: /Users/dsp/src/rye-test/requirements.lock
Creating virtualenv for pip-tools
error: could not write production lockfile for project

Caused by:
    0: unable to create virtualenv folder '/Users/dsp/.rye/pip-tools/cpython@3.12'
    1: No such file or directory (os error 2)
```

### Version Info

rye 0.22.0
commit: 0.21.0+21 (dbfdeeb90 2024-02-07)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true

**Comment by cnpryer** [comment]
> Use an older rye to create a project and sync: rye-old init rye-test && cd rye-test && rye-old sync.

Do you mean that you've tested this on an older version of Rye? If so do you have that `rye-old --version` output? Or do you mean you only reproduced this by running a sync on a project managed by an older version of Rye? If it's the latter, have you tried clearing Rye's home dir?

FWIW I just hit this with
```
❯ rye --version
rye 0.22.0
commit: 0.21.0+17 (e72311698 2024-02-05)
platform: windows (x86_64)
self-python: cpython@3.12
symlink support: false
```

I can try again on my Mac later today. I'm unable to look into this right this moment, but I can try to check it out later.

**Comment by cnpryer** [comment]
If anyone has a moment to test this on d4d2a52405c2c9aa28f071749eafe6921e901ec8 I'd be interested in that.
