### ISSUE TITLE
Rye init could test whether the project name is a valid Python module name

### ISSUE THREAD

**Issue by legendre6891** [mitsuhiko/rye#610]
Hi, this is a promising tool! 

One suggestion is that `rye init` test whether the project name can be imported; here is one "paper cut" associated with it.
```
$ rye init 20240207_hello
$ cd 20240207_hello
$ rye run hello
  File "[my-path-here]/20240207_hello/.venv/bin/hello", line 5
    from 20240207_hello import hello
                 ^
SyntaxError: invalid decimal literal
```

**Comment by mitsuhiko** [comment]
Agreed, this is something that can be improved. Maybe a prefix can be added if it's invalid. Should be an easy fix.
