### ISSUE TITLE
Cannot add tensorflow on 3.10

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/rye#613]
### Steps to Reproduce

1. `rye init`
2. `rye pin 3.10`
3. configure `requires-python = ">=3.10,<3.12"` in `pyproject.toml`
4. run `rye add tensorflow`

### Expected Result

Tensorflow is added to the project

### Actual Result

```
$ rye add tensorflow
error: did not find package 'tensorflow' without using pre-releases.
```

### Version Info

rye 0.22.0
commit: 0.21.0+21 (bdab49bcd 2024-02-06)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true

**Comment by anna-hope** [comment]
I'm still having this issue.

```
rye 0.23.0
commit: 0.23.0 (0fdcdda6c 2024-02-13)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true
```

Pinned python is 3.11.7.
