### ISSUE TITLE
Installation on windows requires VS2015 redist

### ISSUE THREAD

**Issue by kristjanvalur** [mitsuhiko/rye#617]
### Steps to Reproduce

I am working on a project to bootstrap development on fresh windows installs.   I ran into a problem which might be helped by better documentation:

1. open a new windows sandbox  (https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview)
2. run rye installer
3. Watch installer fail, with a missing .dll

I realize this is not something which can be prevented (unless rye is statically linked), but the installation instructions might want to mention this and where to find the required prerequisite (https://www.microsoft.com/en-us/download/details.aspx?id=48145)

After installation, if I uninstall the redistributable, `rye` refuses to run.  So, it is a requirement for both the rye installer and rye itself. However, the python installed by rye (cpython@3.12.1) runs fine, so this is a requiement for rye only.

edit:  Was a bit late to realize that the rye installer and rye is the same executable so, there :)

### Expected Result

installer runs

### Actual Result

installer complains about a missing `VCRUNTIME140.dll`

### Version Info

0.21.0, windows, x64

**Comment by kristjanvalur** [comment]
> It surprises me that the Python version does not require it as it's sort of documented that it does in some cases at least: https://github.com/indygreg/python-build-standalone/blob/94de081efb139cc48a0cdb9c891374ad9b2cdfe2/docs/running.rst#windows
> 

Interesting.  Firing up Python 3.11 here, and using sysinternals procexplorer, I see that it does indeed run
vcruntime140.dll, as well as over 40 other dlls, just in the interactive prompt.


However, the python 12 installed by rye seems to be differently linked, probably statically.  This is the dlls that it uses:
![image](https://github.com/mitsuhiko/rye/assets/6009543/f6460c8b-bf42-4626-9049-13a3d4a5a96d)


> You are right that at the very least the documentation needs to provide this. I'm not entirely sure what the correct solution here is. Ideally one would not need to document it but the installer actually also ensures the redist is installed. Static linking does not seem ideal.

Well, Rust is known for creating standalone binaries, would be interesting to see how much the .exe grows when static linking.  Rust probably isn't using much of the c runtime... 

I see that you made a PR, will be watching it.

**Comment by kristjanvalur** [comment]
Just checked running Rye in my sandbox, sysinternals reports that the only non-system dll it is running is inded vcruntime140.dll:
![image](https://github.com/mitsuhiko/rye/assets/6009543/5bbb501b-9d5b-4f1f-b364-14a5bc6217c7)

**Comment by mitsuhiko** [comment]
In that case I am not entirely opposed to statically linking vcruntime. Unfortunately I don't have my windows PC until next week again so I can't test that the PR actually fixes that.
