### ISSUE TITLE
warning: unable to mark virtualenv ignored for cloud sync: Not supported (os error 95)

### ISSUE THREAD

**Issue by impredicative** [mitsuhiko/rye#632]
### Steps to Reproduce

When I run `rye sync`, I see the warning message:

    warning: unable to mark virtualenv ignored for cloud sync: Not supported (os error 95)

`rye` then proceeds normally.

### Expected Result

I am not expecting to see any such message.

### Actual Result

```
$ rye sync
Reusing already existing virtualenv
warning: unable to mark virtualenv ignored for cloud sync: Not supported (os error 95)
```

### Version Info

```
rye 0.22.0
commit: 0.22.0 (203a0f33f 2024-02-09)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true
```

**Comment by mitsuhiko** [comment]
@impredicative can you share which file system you are using?

**Comment by mitsuhiko** [comment]
#633 will no longer show this error when venv marking is disabled. I will also improve this message. But I not understand why setting this attribute fails in the first place. ext4 should support it.

**Comment by bluss** [comment]
Also fails with same warning on my ext4 filesystem, ubuntu 22.04

Not sure which features are needed, but the following are present in tune2fs. Mounted relatime.

```
tune2fs 1.46.5 (30-Dec-2021)
Filesystem volume name:   <none>
Last mounted on:          /
Filesystem UUID:          
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize metadata_csum
Filesystem flags:         signed_directory_hash 
Default mount options:    user_xattr acl
```

**Comment by bluss** [comment]
I can't write arbitrary xattrs on files:

```
$ touch testfile
$ xattr -w testattribute value testfile
[Errno 95] Operation not supported: b'testfile'
```

But I am allowed to use the user namespace
```
$ xattr -w user.testattribute value testfile
$ xattr -l testfile
user.testattribute: value
```

**Comment by bluss** [comment]
In the current rye version, this warning comes up not just on sync, but on every "rye run". That seems bit excessive, why is it doing writing changes to the venv on every such command?

**Comment by mitsuhiko** [comment]
That is a very good question. It should not.

**Comment by ngmisl** [comment]
when I try to source into the venv creaty by rye it literally does not activate it

**Comment by mitsuhiko** [comment]
@ngmisl can you please share what you are running, what is happening and what you are expecting instead on a new issue?
