### ISSUE TITLE
`rye install jupyter` does not add `jupyter` to ~/.rye/shims

### ISSUE THREAD

**Issue by stevenheidel** [mitsuhiko/rye#65]
### Steps to Reproduce

1. Run `rye install pycowsay` - verify that pycowsay appears in ~/.rye/shims
2. Run `rye install jupyter`

### Expected Result

The `jupyter` command is added to ~/.rye/shims and can be run from the terminal if ~/.rye/shims is on the PATH.

### Actual Result

No scripts are added to ~/.rye/shims, and there's an error message:
`warning: installed package did not expose any scripts`

### Version Info

```
rye 0.1.0
commit: unknown (01cbe9681 2023-04-28)
platform: macos (aarch64)
self-python: cpython@3.10
```

(Aside: `rye --version` currently prints to stderr, which means you have to do `rye --version 2>&1 | pbcopy`. If it printed to stdout it would make this a bit easier: `rye --version | pbcopy`)

**Comment by mitsuhiko** [comment]
I'm assuming that this is because jupyter does not actually come with any scripts but they come from some dependency of jupyter. I will check if the logic for promoting scripts could/should take some dependencies into account.

**Comment by mitsuhiko** [comment]
This is now fixed. But you need to pass a flag:

```
$ rye install jupyter -f --sub-package jupyter-core
```

That's because jupyter itself does not install any scripts.

**Comment by stevenheidel** [comment]
I think you mean `rye install jupyter --include-dep jupyter-core`, but yes that works now.

**Comment by mitsuhiko** [comment]
Sorry yes, last minute rename :)

**Comment by quinn-dougherty** [comment]
how can I get this to work with `pyproject.toml`, for per-project installation in an ephemeral shell?

**Comment by quinn-dougherty** [comment]
update: 
```
$ cat ~/.config/fish/fish_variables
SETUVAR fish_user_paths:/home/qd/\x2erye/shims
```
after running `set -Ua fish_user_paths "$HOME/.rye/shims"`

I fixed the `\x2e` and replaced it with `.`, but still didn't work.
