### ISSUE TITLE
New command `rye shell`

### ISSUE THREAD

**Issue by souliane** [mitsuhiko/rye#653]
I know it's as easy as typing `. .venv/bin/activate`, but I would love to be able to do it with `rye shell` (the command name might not be adequate, but this reminds of `poetry shell`).

rye is built on top of other tools, but I understand that the goal is to propose a unified interface, and those other tools should remain in a blackbox to also keep a consistent workflow when one tool is changed for another. So I think that it would make a lot of sense to add a command for activating the virtualenv.

**Comment by dsp** [comment]
Rye used to have `rye shell` but it was removed in ee92aeb4a504942278ae8a7d7a6d940e88570213. It's documentation said:
```
**Warning:** this feature is inherently buggy as shells do not support portable APIs
to enable this functionality.  This command might to away if it cannot be fixed.
```

I think, unless we find a relaible, portable way of enabling a virtual environemnt from a command, there will not be a `rye shell`. Sourcing `.venv/bin/activate` is the most robust way, and maybe an alias in your shell `alias venv=source .venv/bin/activate` might do the trick here.

**Comment by selectnull** [comment]
@souliane For activating the venv, you might want to check out [ave](https://github.com/selectnull/ave) It's a simple shell script that allows you to type `ave` in your project root and voila... the virtual environment is activated. I've been using it for more that a decade now. It's trying to be smart about the location of venv, I've started using rye only recently so I made it work with it as well. It's really easy to type, easier than `rye shell` and certainly easier that `. .venv/bin/activate`

Also, working mostly with Django, I got used to type `django-admin shell` and have certain expectations about what it does, I guess many Django users would have the same expectations. So I kinda played with the idea and just hacked together this:

Create shell.py file in your project root.

``` python
def shell():
    import code
    code.interact(local=locals())

if __name__ == '__main__':
    shell()
```

Add this to `pyproject.toml`

[tool.rye.scripts]
shell = { cmd = "python shell.py", env = { ...whatever you need, if you need it } }

And start a Python shell with `rye run shell`.

Like I said, having Django experience, I expected `rye shell` to start a Python shell, not activate the venv. Not saying that rye should or should not implement the shell, but if it does I wouldn't mind actually starting the shell.
