### ISSUE TITLE
Python Shim choices are confusing

### ISSUE THREAD

**Issue by bancek** [mitsuhiko/rye#663]
For someone installing Rye for the first time I found the following question very confusing:

```
Determine Rye's python Shim behavior outside of Rye managed projects ›
 - Make Rye's own Python distribution available
 - Transparently pass through to non Rye (system, pyenv, etc.) Python
```

When I first read "Make Rye's own Python distribution available" I didn't understand what it actually meant. Now when I'm writing this issue and after reading the source it makes sense. But it will probably be confusing for other first time users.

I think it should tell the user what the installer will do. Something like this:

```
Rye installer will override "python" and "python3" commands for your user.
What should running "python" or "python3" do when you are not inside a Rye managed project?
 - Run python installed by Rye
 - Run the old default python (provided by your OS, pyenv, etc.): "/usr/local/opt/python@3.9/bin/python3"
```

Maybe the installer should also display a link to https://rye-up.com/guide/shims/

**Comment by mitsuhiko** [comment]
Yeah I'm not happy with the dialog choices presented. I quite like your wording.
