### ISSUE TITLE
rye config --set uses quotes around booleans

### ISSUE THREAD

**Issue by tfriedel** [mitsuhiko/rye#688]
### Steps to Reproduce

run rye config --set behavior.use-uv=true

### Expected Result

~/.rye/config.toml looks like

[behavior]
global-python = true
use-uv = true

### Actual Result

~/.rye/config.toml looks like

[behavior]
global-python = true
use-uv = "true"

Not sure if this is actually a problem, besides the fact that it looks inconsistent.

### Version Info

rye 0.24.0
commit: 0.24.0 (8d56aa18a 2024-02-15)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true

(I'm using wsl2)

**Comment by j178** [comment]
You should use `rye config --set-bool behavior.use-uv=true` to set a boolean flag.

**Comment by mitsuhiko** [comment]
Yeah. Today the config system doesn't have a schema so you need to be explicit unfortunately.
