### ISSUE TITLE
Fail to bootstrapping on Windows

### ISSUE THREAD

**Issue by qcts33** [mitsuhiko/rye#709]
### Steps to Reproduce

a fresh install of rye on windows:
```
rye-x86_64-windows.exe self install
```

### Expected Result

Bootstrapping rye internals

### Actual Result

failed by no matching uv
```
Bootstrapping rye internals
Downloading cpython@3.12.1
Checking checksum
success: Downloaded cpython@3.12.1
Upgrading pip
Installing internal dependencies
ERROR: Could not find a version that satisfies the requirement uv==0.1.5 (from versions: 0.0.3.dev0.win32, 0.0.2.dev1)
ERROR: No matching distribution found for uv==0.1.5
error: failed to initialize virtualenv (install dependencies)
```

### Version Info

```
rye-x86_64-windows.exe --version
rye 0.25.0
commit: 0.25.0 (d8e00cea1 2024-02-19)
platform: windows (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: false
```

**Comment by mitsuhiko** [comment]
Is this a 64bit intel windows or an ARM64 one?

**Comment by qcts33** [comment]
This is a 64bit intel

**Comment by mitsuhiko** [comment]
I cannot reproduce this. I'm very confused why it does not find `uv` since it's published. My only explanation is that for whatever reason it picks up the wrong abi tag. Are you running this in WSL or something non standard?

**Comment by qcts33** [comment]
I'm running it directly. There does seem to be something wrong with my system, as no one has reported the same problem. 
I previously installed `rye` using [scoop](https://scoop.sh/), but I cleaned up that installation after noticing the problem and tried again using the standard method.  I don't think `scoop` is causing the problem. However, I will keep trying to find out what the problem is.

**Comment by qcts33** [comment]
I finally get it working after a careful cleanup of all the leftovers from previous `pip` installs. However, I am still not sure what exactly the problem is.
