### ISSUE TITLE
Package resolution defaults to latest, not latest stable

### ISSUE THREAD

**Issue by orpheuslummis** [mitsuhiko/rye#71]
Conventionally, the default behavior of package resolution is to use latest *stable* versions. Perhaps the behavior of using the very latest / prerelease could be behind a flag of the `add` command. `pip` uses the flag `--pre` for that. (https://pip.pypa.io/en/stable/cli/pip_install/#install-pre)

As an example: latest *stable* `pydantic` (https://pypi.org/project/pydantic/) is version `1.10.7`, latest `pydantic` (as found on https://pypi.org/simple/pydantic/) is version `2.0a3`. Currently, `rye` selects the alpha version.

**Comment by cnpryer** [comment]
Could hack this together like [this](https://github.com/mitsuhiko/rye/compare/main...cnpryer:rye:add-pre), but I'm not sure if this calls for something more robust.
