### ISSUE TITLE
constrain requires-python version work not proper

### ISSUE THREAD

**Issue by CharlesChen0823** [mitsuhiko/rye#74]
### Steps to Reproduce

1. `rye init testrye`
2. `rye pin cpython@3.7`
3. `rye sync`

### Expected Result

execute success and pyproject.toml requires-python version set as pin >=3.7

### Actual Result

Downloading cpython@3.7.9
success: Downloaded cpython@3.7.9
Initializing new virtualenv in /Users/charles/program/python/testrye/.venv
Python version: cpython@3.7.9
Generating production lockfile: /Users/charles/program/python/testrye/requirements.lock
Generating dev lockfile: /Users/charles/program/python/testrye/requirements-dev.lock
Installing dependencies
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Obtaining file:///. (from -r /var/folders/z4/4q0sj3vn5fvbmp8v961pnkl40000gn/T/tmpwi9yy1uk (line 1))
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of testrye to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'testrye' requires a different Python: 3.7.9 not in '>=3.8'
Traceback (most recent call last):
  File "/Users/charles/.rye/self/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
  File "/Users/charles/.rye/self/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/charles/.rye/self/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/charles/.rye/self/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/charles/.rye/self/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/charles/.rye/self/lib/python3.10/site-packages/piptools/scripts/sync.py", line 174, in cli
    sync.sync(
  File "/Users/charles/.rye/self/lib/python3.10/site-packages/piptools/sync.py", line 244, in sync
    run(  # nosec
  File "/Users/charles/.rye/py/cpython@3.10.9/install/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/charles/program/python/testrye/.venv/bin/python', '-m', 'pip', 'install', '-r', '/var/folders/z4/4q0sj3vn5fvbmp8v961pnkl40000gn/T/tmpwi9yy1uk', '--index-url', 'http://mirrors.aliyun.com/pypi/simple', '--trusted-host', 'mirrors.aliyun.com', '--python=/Users/charles/program/python/testrye/.venv/bin/python']' returned non-zero exit status 1.
Error: Installation of dependencies failed

### Version Info

rye 0.1.0
commit: unknown (74937e37b 2023-04-29)
platform: macos (x86_64)
self-python: cpython@3.10

**Comment by cnpryer** [comment]
I don't believe a 3.7 build is available for my system, otherwise I'd try to repo this. 
```
OS: macos 13.3.1
Chip: Apple M1 Max
```
Could you share your pyproject.toml?

**Comment by CharlesChen0823** [comment]
current execute `rye init testrye` the default `pyproject.toml` is:
```
[project]
name = "testrye"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "", email = "" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
```
2. when you `rye pin cpython@3.7`, then `pyproject.toml` is not modify and the `requires-python` is still `>=3.8`, which is not proper.

**Comment by cnpryer** [comment]
Could you give https://github.com/mitsuhiko/rye/pull/75 a shot?

**Comment by cnpryer** [comment]
Actually I'm not even sure this makes sense to do. AFAIK `rye pin` is not meant to manage the requires-python. It's to pin a Python version to the project environment.

**Comment by cnpryer** [comment]
So in your case you should just update the requires-python to match your needs. This is core metadata about the workspace package. Maybe it makes sense to say if my pinned version is older than the marked requires-python, then we updated it. But if it's greater and you're just pinning an updated Python version that doesn't necessarily mean you want to change the requires-python market.

**Comment by cnpryer** [comment]
Could also just emit a warning when the pinned version is older than the required.

**Comment by CharlesChen0823** [comment]
In my view, if pin version is older than the marked requires-python, then update it is better. And emit a warning to the user, the requires-python has been modified to the  older one.

**Comment by cnpryer** [comment]
This could get confusing for some users though. When I think of the `rye pin` command I think of a command I'd want to use to manage my "current" Python version. That should be from within the constraints of the project I'm working on.

It might make more sense to handle this similar to how a pip install would fail if a package you're installing isn't compatible with it. If you want `pin` to make a change to the constraints it probably should be opt-in and explicit. Something like `rye pin --force`.
