### ISSUE TITLE
Change default install target to `~/.local/rye`

### ISSUE THREAD

**Issue by pepoluan** [mitsuhiko/rye#756]
In the interest of preventing more clutter in the `~` directory, I suggest changing the default install dir to `~/.local/rye` rather than the current default of `~/.rye`

**Comment by mitsuhiko** [comment]
You can rebind it with `RYE_HOME`. Personally I do not like when tools put stuff in different places and I follow the pattern from cargo here.

Maybe this will change later since uv tools have the things at different locations but for now I will close this issue.
