### ISSUE TITLE
A local sync service to replace rye sync

### ISSUE THREAD

**Issue by cnpryer** [mitsuhiko/rye#76]
IIRC Cargo uses fingerprints to determine when updates have been made to the project and its environment. It would be nice to have `rye sync` managed by a kind of watch service that does something like this.

This probably makes more sense in the future with faster sync operations, but I thought I could propose it for the wishlist.

**Comment by mitsuhiko** [comment]
Yeah `rye sync` is a bit of a clutch. Longer term I think it would be possible to make the operations of `rye sync` significantly faster, but that's today not an option based on what's underneath. A somewhat temporary solution could be to just use content hashes cached in the .venv to pick up on dependency changes and to automatically run `sync` as needed.

**Comment by mitsuhiko** [comment]
I'm going to track this as part of #114. It's mostly a duplicate.
