### ISSUE TITLE
platform specific `--no-dependencies` support

### ISSUE THREAD

**Issue by lrecknagel** [mitsuhiko/rye#77]
* 1st - thanks for all efforts put into rye, really a pleasure to use!

## Issue description
* I currently struggle to solve a issue with: https://github.com/pimoroni/inky under macos.
* I cannot add / sync it with rye because it has a dependency (`spidev`) which is linux only
* For local debugging on macos `spidev` is not needed

## Suggestion
* It would be awesome if rye could add a way to make a dependency systemspecific with `--no-dependencies`

Looking forward to discuss (hopefully) possible options 🚀

**Comment by mitsuhiko** [comment]
This is a pretty good case of a typical example of how declared dependencies often push a user to require an explicit override. I came across a few of these cases myself too but not in a while. I'm quite curious if this is a common occurrence in the ecosystem these days and what the general guidance is to resolve it.

**Comment by lrecknagel** [comment]
Totally agree - but I am not to deep into the python ecosystem to be fair. Maybe you know someone to resolve this question on a higher level. Could you give an advice for a "shorterm" hack to make it work?

**Comment by mitsuhiko** [comment]
While this is not the prettiest solution (and does not support markers yet), you can dig yourself out of this hole now:

```
$ rye add inky
$ rye add --exclude spidev
$ rye sync
```
