### ISSUE TITLE
Adding dependency by version control system

### ISSUE THREAD

**Issue by orpheuslummis** [mitsuhiko/rye#78]
### Steps to Reproduce

`rye add git+ssh://git@git.example.com/MyProject`, or add it as dependency in `project.toml`

### Expected Result

Support of adding dependency via version control system is expected.
https://pip.pypa.io/en/stable/topics/vcs-support/

### Actual Result

`Expected end or semicolon (after name and no valid version specifier) git+https://...`

### Version Info

```
rye 0.1.0
commit: unknown (aa5594994 2023-04-28)
platform: linux (x86_64)
self-python: cpython@3.10
```

**Comment by mitsuhiko** [comment]
You can add them with `rye add package-name --git=ssh://git@git.example.com/MyProject`. The package name is mandatory and there is no auto discovery today.
