### ISSUE TITLE
Shim launches rye

### ISSUE THREAD

**Issue by kabouzeid** [mitsuhiko/rye#8]
I don't use the shims, but I just noticed that they're all pointing to the `rye` binary.

```
➜ ls -l ~/.rye/shims/
total 0
lrwxrwxrwx 1 abou_zeid hiwi 30 Apr 23 20:43 python -> /home/abou_zeid/.cargo/bin/rye*
lrwxrwxrwx 1 abou_zeid hiwi 30 Apr 23 20:43 python3 -> /home/abou_zeid/.cargo/bin/rye*
```

**Comment by mitsuhiko** [comment]
That's where they should point to!

**Comment by kabouzeid** [comment]
Why should `python` be an alias to `rye`? For me this doesn't delegate to python and just launches rye.

**Comment by mitsuhiko** [comment]
@kabouzeid

**Comment by kabouzeid** [comment]
Works, thx.
