### ISSUE TITLE
Add "python-version" field to pyproject.toml for pinning Python version

### ISSUE THREAD

**Issue by Betagmr** [mitsuhiko/rye#96]
Currently, the Python version is pinned by creating a file called `.python-version` in the project directory. However, some developers may prefer to have this information stored in the `pyproject.toml `and not having it as an extra file. I suggest having the option to add it as a new field called "python-version" to the [tool.rye] section in the `pyproject.toml` file. 

```
[tool.rye]
managed = true
python-version = 3.10.6
```

**Comment by cnpryer** [comment]
`.python-version` is familiar to probably a good portion of potential users because of `pyenv` -- if I had to guess.

I do agree though that it would be nice to limit configuration file sprawl.

**Comment by Betagmr** [comment]
One approach could be to rewrite the `load_python_version` function to check if there is no `.python-version` file inside `pyproject.toml` .

**Comment by cnpryer** [comment]
Well to play devil's advocate leaving it the way it is does have the benefit of being compatible with an existing `pyenv` workflow.

**Comment by cnpryer** [comment]
> One approach could be to rewrite the `load_python_version` function to check  inside `pyproject.toml` if there is no `.python-version` file.

The problem I see with this is going down this route just leaves room for options. I'd prefer `rye` to just make a decision and stick with it.

Even Ofek (creator of `hatch`) mentions that while configurability is good, a lot of the time users are looking for recommendations. 

So how much do you allow configurability for vs picking something and sticking with it.

**Comment by Betagmr** [comment]
> > One approach could be to rewrite the `load_python_version` function to check  inside `pyproject.toml` if there is no `.python-version` file.
> 
> The problem I see with this is going down this route just leaves room for options. I'd prefer `rye` to just make a decision and stick with it.
> 
> Even Ofek (creator of `hatch`) mentions that while configurability is good, a lot of the time users are looking for recommendations.
> 
> So how much do you allow configurability for vs picking something and sticking with it?

I introduced the idea of having both because in many other tools like `ruff` there is always the option to have a .config file or a field in the `pyproject.toml` .

As you say, if I had to stick to one I would prefer not having the extra file.  It's a common case when you use `pyenv` to avoid creating the `.python-version`, and instead use `pyenv shell VERSION` to create the virtualenv with that python version.

**Comment by mitsuhiko** [comment]
I'm also not a fan of this file, but it's the closest there is to a standard today I believe.

**Comment by con-f-use** [comment]
Another thought, if the package pins [requires-python](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#requires-python) in `pyproject.tom` to a single version, i.e. uses no qualifier, isn't that thought of like pinned? The platfrom can be auto-detected, only thing unknown might be and the interpreter "flavor" (don't know what the term is, I mean: pypy, cpython, etc).

**Comment by mitsuhiko** [comment]
No, i think that makes a lot of sense. The caveat is that with workspaces it would only honor the toplevel one.

**Comment by T-256** [comment]
https://github.com/mitsuhiko/rye/pull/117 is Great,
I suggest a new fallback layer to fix https://github.com/mitsuhiko/rye/issues/96:

* When creating a new project, `tool.rye.python` is written in config file. The `requires-python` key is set to 3.8 by default.
* When a virtualenv is created, `.python-version` is preferred, otherwise it falls back to `tool.rye.python`, if that config not exists it falls back to `requires-python`.

`.python-version` > `tool.rye.python` > `requires-python`

**Comment by con-f-use** [comment]
Why the `tool.rye.python`?

**Comment by T-256** [comment]
@con-f-use the `python` config name is where `hatch` uses it, so I thought it may reasonable to use it here too.
`$ rye init`
pyptoject.toml:
```toml
[project]
...
requires-python = ">= 3.8"

[tool.rye]
managed = true
python = "3.11.1"
```
here `python 3.11.1` will used if there is not `.python-version` file instead of `python 3.8`.

**Comment by con-f-use** [comment]
So my point of view is: either the exact python version is crucial to the project and it doesn't work (well) with another python, in which case it should be in `pyproject.toml` as `requires-python == "3.10.10"` or the project has a softer python version requirement, in which case the exact python version, is a user-environment thing and shouldn't be in `pyproject.toml` at all. The user is essentially free to choose, you wouldn't commit it to the repo. That latter case is covered by `.python-version`.

**Comment by mitsuhiko** [comment]
I'm reopening this given the discussion but I have to admit that I'm not entirely sure what the benefit of that extra key is right now.

**Comment by T-256** [comment]
> That case is covered by `.python-version`. So the extra key doesn't add usefulness, beyond the vauge "some people may find it prettier". In my mind, ".python-version" is to the python interpreter, what lockfiles are to virtualenvs.

It makes sense, python-version file does the job currently. my suggestion was not to ignore this file or decreasing its priority. I just said we could have one less file in project structure.


> I'm reopening this given the discussion but I have to admit that I'm not entirely sure what the benefit of that extra key is right now.

Thats correct, I also don't think it's correct time to support extra options when project even isn't going to stable.
Sorry for make you confused

**Comment by con-f-use** [comment]
> Sorry for make you confused

I thought that was my job! :wink:

**Comment by con-f-use** [comment]
> Sorry for make you confused

I thought that was my job! :wink:

**Comment by doolio** [comment]
> I'm also not a fan of this file, but it's the closest there is to a standard today I believe.

`pyproject.toml` is a PEP standard and all tools are encouraged to adopt it. Using a `.python-version` file because it is what `pyenv` uses so it is familiar to people is why the python tooling ecosystem is a mess. Especially since `rye` removes the need for `pyenv`. The community has to come together to use the agreed standards and shun all other options. So if I could I would vote to drop this file and use `pyproject.toml` instead.
