### ISSUE TITLE
Generate LICENSE file(s) for rye's init command

### ISSUE THREAD

**Issue by patrickarmengol** [mitsuhiko/rye#99]
rye's `init` command already references an MIT license in the default generated `README.md` and `pyproject.toml`. Should it also generate the relevant `LICENSE` file?

Perhaps rye could also add a cli option for `init` that lets the user specify which license(s) they would like to use, specified by [SPDX identifiers](https://spdx.org/licenses/). 

```sh
rye init --license "Apache-2.0"
```

**Comment by ischaojie** [comment]
[hatch](https://github.com/pypa/hatch) generates an empty license file during initialization, and it is up to the user to add the details.

**Comment by CharlesChen0823** [comment]
the optional args `license` should check.

**Comment by ischaojie** [comment]
Also, I think all these custom fields should be filled in interactively by the user, for example `rye init --interactive` will go to interactive mode, where the user can specify name, description, etc.

**Comment by cnpryer** [comment]
> Also, I think all these custom fields should be filled in interactively by the user, for example `rye init --interactive` will go to interactive mode, where the user can specify name, description, etc.

Is this preference or is there something missing by not having a more interactive experience? I'd prefer rye doesn't do this, but maybe I'm missing something.

**Comment by patrickarmengol** [comment]
> [hatch](https://github.com/pypa/hatch) generates an empty license file during initialization, and it is up to the user to add the details.

I'm not sure why you end up with empty files, but hatch generated license files are filled for me. It even fills in my author name where possible. Perhaps you are giving it an invalid SPDX identifier. 

Looks like it [reaches out to download license files](https://github.com/pypa/hatch/blob/master/src/hatch/template/default.py#L43) from the [SPDX license-list-data repo](https://github.com/spdx/license-list-data/tree/main/text). 

 
> And https://peps.python.org/pep-0639/

hatch / hatchling supports this PEP, and uses it in generated `pyproject.toml`, but the PEP is still a draft, so maybe we can hold off until it's accepted?

**Comment by mitsuhiko** [comment]
This is implemented now.
